In [1]:
import pandas as pd

pd.options.mode.chained_assignment = None
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [2]:
df = pd.read_csv('real_estate_data.csv',sep='\t')

In [3]:
df.columns

Index(['total_images', 'last_price', 'total_area', 'first_day_exposition',
       'rooms', 'ceiling_height', 'floors_total', 'living_area', 'floor',
       'is_apartment', 'studio', 'open_plan', 'kitchen_area', 'balcony',
       'locality_name', 'airports_nearest', 'cityCenters_nearest',
       'parks_around3000', 'parks_nearest', 'ponds_around3000',
       'ponds_nearest', 'days_exposition'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23699 entries, 0 to 23698
Data columns (total 22 columns):
total_images            23699 non-null int64
last_price              23699 non-null float64
total_area              23699 non-null float64
first_day_exposition    23699 non-null object
rooms                   23699 non-null int64
ceiling_height          14504 non-null float64
floors_total            23613 non-null float64
living_area             21796 non-null float64
floor                   23699 non-null int64
is_apartment            2775 non-null object
studio                  23699 non-null bool
open_plan               23699 non-null bool
kitchen_area            21421 non-null float64
balcony                 12180 non-null float64
locality_name           23650 non-null object
airports_nearest        18157 non-null float64
cityCenters_nearest     18180 non-null float64
parks_around3000        18181 non-null float64
parks_nearest           8079 non-null float64
ponds_around3000        18181 non-null float64
ponds_nearest           9110 non-null float64
days_exposition         20518 non-null float64
dtypes: bool(2), float64(14), int64(3), object(3)
memory usage: 3.7+ MB

balcony, is_apartment, open_plan, studio

In [5]:
df['balcony'] = df['balcony'].fillna(0).astype(int)
df['is_apartment'] = df['is_apartment'].fillna(0).astype(int)
df['open_plan'] = df['open_plan'].fillna(0).astype(int)
df['studio'] = df['studio'].fillna(0).astype(int)

In [8]:
df.assign(
    balcony = lambda x: x['balcony'].fillna(0).astype(int),
    is_apartment = lambda x: x['is_apartment'].fillna(0).astype(int),
    open_plan = lambda x: x['open_plan'].fillna(0).astype(int),
    studio = lambda x: x['studio'].fillna(0).astype(int),
    living_to_total = lambda x: x['living_area'] / x['total_area']
)

,total_images,last_price,total_area,first_day_exposition,rooms,ceiling_height,floors_total,living_area,floor,is_apartment,...,balcony,locality_name,airports_nearest,cityCenters_nearest,parks_around3000,parks_nearest,ponds_around3000,ponds_nearest,days_exposition,living_to_total
0,20,13000000.000,108.000,2019-03-07T00:00:00,3,2.700,16.000,51.000,8,0,...,0,Санкт-Петербург,18863.000,16028.000,1.000,482.000,2.000,755.000,nan,0.472
1,7,3350000.000,40.400,2018-12-04T00:00:00,1,nan,11.000,18.600,1,0,...,2,посёлок Шушары,12817.000,18603.000,0.000,nan,0.000,nan,81.000,0.460
2,10,5196000.000,56.000,2015-08-20T00:00:00,2,nan,5.000,34.300,4,0,...,0,Санкт-Петербург,21741.000,13933.000,1.000,90.000,2.000,574.000,558.000,0.612
3,0,64900000.000,159.000,2015-07-24T00:00:00,3,nan,14.000,nan,9,0,...,0,Санкт-Петербург,28098.000,6800.000,2.000,84.000,3.000,234.000,424.000,nan
4,2,10000000.000,100.000,2018-06-19T00:00:00,2,3.030,14.000,32.000,13,0,...,0,Санкт-Петербург,31856.000,8098.000,2.000,112.000,1.000,48.000,121.000,0.320
5,10,2890000.000,30.400,2018-09-10T00:00:00,1,nan,12.000,14.400,5,0,...,0,городской посёлок Янино-1,nan,nan,nan,nan,nan,nan,55.000,0.474
6,6,3700000.000,37.300,2017-11-02T00:00:00,1,nan,26.000,10.600,6,0,...,1,посёлок Парголово,52996.000,19143.000,0.000,nan,0.000,nan,155.000,0.284
7,5,7915000.000,71.600,2019-04-18T00:00:00,2,nan,24.000,nan,22,0,...,2,Санкт-Петербург,23982.000,11634.000,0.000,nan,0.000,nan,nan,nan
8,20,2900000.000,33.160,2018-05-23T00:00:00,1,nan,27.000,15.430,26,0,...,0,посёлок Мурино,nan,nan,nan,nan,nan,nan,189.000,0.465
9,18,5400000.000,61.000,2017-02-26T00:00:00,3,2.500,9.000,43.600,7,0,...,2,Санкт-Петербург,50898.000,15008.000,0.000,nan,0.000,nan,289.000,0.715
10,5,5050000.000,39.600,2017-11-16T00:00:00,1,2.670,12.000,20.300,3,0,...,0,Санкт-Петербург,38357.000,13878.000,1.000,310.000,2.000,553.000,137.000,0.513
11,9,3300000.000,44.000,2018-08-27T00:00:00,2,nan,5.000,31.000,4,0,...,1,Ломоносов,48252.000,51677.000,0.000,nan,0.000,nan,7.000,0.705
12,10,3890000.000,54.000,2016-06-30T00:00:00,2,nan,5.000,30.000,5,0,...,0,Сертолово,nan,nan,nan,nan,nan,nan,90.000,0.556
13,20,3550000.000,42.800,2017-07-01T00:00:00,2,2.560,5.000,27.000,5,0,...,1,Петергоф,37868.000,33058.000,1.000,294.000,3.000,298.000,366.000,0.631
14,1,4400000.000,36.000,2016-06-23T00:00:00,1,nan,6.000,17.000,1,0,...,0,Пушкин,20782.000,30759.000,0.000,nan,1.000,96.000,203.000,0.472
15,16,4650000.000,39.000,2017-11-18T00:00:00,1,nan,14.000,20.500,5,0,...,1,Санкт-Петербург,12900.000,14259.000,1.000,590.000,1.000,296.000,19.000,0.526
16,11,6700000.000,82.000,2017-11-23T00:00:00,3,3.050,5.000,55.600,1,0,...,0,Санкт-Петербург,22108.000,10698.000,3.000,420.000,0.000,nan,397.000,0.678
17,6,4180000.000,36.000,2016-09-09T00:00:00,1,nan,17.000,16.500,7,0,...,1,Санкт-Петербург,33564.000,14616.000,0.000,nan,1.000,859.000,571.000,0.458
18,8,3250000.000,31.000,2017-01-27T00:00:00,1,2.500,5.000,19.400,2,0,...,1,Санкт-Петербург,44060.000,10842.000,1.000,759.000,0.000,nan,168.000,0.626
19,16,14200000.000,121.000,2019-01-09T00:00:00,3,2.750,16.000,76.000,8,0,...,0,Санкт-Петербург,38900.000,12843.000,0.000,nan,0.000,nan,97.000,0.628
20,12,6120000.000,80.000,2017-09-28T00:00:00,3,2.700,27.000,48.000,11,0,...,2,посёлок Парголово,53134.000,19311.000,0.000,nan,0.000,nan,74.000,0.600
21,13,3200000.000,31.600,2018-03-14T00:00:00,1,nan,5.000,16.900,2,0,...,1,Санкт-Петербург,36064.000,9722.000,1.000,248.000,0.000,nan,310.000,0.535
22,20,5000000.000,58.000,2017-04-24T00:00:00,2,2.750,25.000,30.000,15,0,...,2,деревня Кудрово,nan,nan,nan,nan,nan,nan,60.000,0.517
23,11,2950000.000,32.000,2016-10-29T00:00:00,1,2.600,9.000,17.700,9,0,...,0,Санкт-Петербург,15414.000,14211.000,2.000,517.000,1.000,190.000,615.000,0.553
24,8,6500000.000,97.200,2015-10-31T00:00:00,2,nan,3.000,46.500,1,0,...,0,Санкт-Петербург,20052.000,2336.000,3.000,411.000,3.000,124.000,265.000,0.478
25,3,6800000.000,76.000,2015-10-01T00:00:00,2,2.750,23.000,39.000,18,0,...,2,Санкт-Петербург,34967.000,14640.000,0.000,nan,1.000,564.000,300.000,0.513
26,6,4050000.000,60.000,2017-04-28T00:00:00,4,nan,5.000,43.000,4,0,...,0,Санкт-Петербург,11580.000,10510.000,0.000,nan,1.000,95.000,265.000,0.717
27,20,7100000.000,70.000,2017-05-12T00:00:00,3,2.600,17.000,49.000,11,0,...,0,Санкт-Петербург,29197.000,11456.000,2.000,452.000,1.000,779.000,151.000,0.700
28,8,4170000.000,44.000,2017-12-13T00:00:00,1,2.900,6.000,20.800,1,0,...,1,Пушкин,18557.000,30710.000,0.000,nan,1.000,118.000,74.000,0.473
29,9,8600000.000,100.000,2016-04-09T00:00:00,3,nan,19.000,52.000,15,0,...,0,Санкт-Петербург,30394.000,11526.000,1.000,532.000,1.000,896.000,125.000,0.520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23669,8,3000000.000,34.100,2017-11-10T00:00:00,1,nan,9.000,17.000,3,0,...,1,Колпино,24687.000,30473.000,0.000,nan,1.000,741.000,74.000,0.499
23670,9,2450000.000,45.600,2018-02-08T00:00:00,1,2.800,9.000,nan,2,0,...,0,поселок городского типа Синявино,nan,nan,nan,nan,nan,nan,45.000,nan
23671,3,3450000.000,35.300,2017-04-14T00:00:00,1,2.500,9.000,17.500,4,0,...,2,Санкт-Петербург,21435.000,15261.000,1.000,334.000,1.000,232.000,21.000,0.496
23672,5,3000000.000,30.800,2016-06-08T00:00:00,1,nan,5.000,16.100,3,0,...,0,Санкт-Петербург,44614.000,14193.000,2.000,258.000,0.000,nan,808.000,0.523
23673,9,3100000.000,23.000,2018-03-19T00:00:00,1,2.800,9.000,12.600,1,0,...,2,Санкт-Петербург,11813.000,11881.000,1.000,262.000,1.000,442.000,41.000,0.548
23674,10,5950000.000,56.000,2019-03-05T00:00:00,3,nan,8.000,32.100,3,0,...,0,Санкт-Петербург,32139.000,9217.000,0.000,nan,2.000,303.000,nan,0.573
23675,8,3550000.000,39.500,2016-10-03T00:00:00,1,nan,16.000,19.000,13,0,...,0,Санкт-Петербург,25740.000,14951.000,0.000,nan,0.000,nan,721.000,0.481
23676,19,3550000.000,36.400,2016-06-08T00:00:00,1,nan,16.000,14.900,13,0,...,0,Санкт-Петербург,32228.000,11884.000,1.000,701.000,0.000,nan,70.000,0.409
23677,8,2450000.000,35.000,2018-10-26T00:00:00,1,2.600,5.000,18.000,4,0,...,0,Всеволожск,nan,nan,nan,nan,nan,nan,28.000,0.514
23678,10,3500000.000,43.000,2016-05-19T00:00:00,2,2.500,3.000,26.100,2,0,...,1,Пушкин,15823.000,27977.000,0.000,nan,1.000,1134.000,252.000,0.607
23679,0,2500000.000,35.000,2017-12-08T00:00:00,1,nan,9.000,nan,4,0,...,0,Сосновый Бор,nan,nan,nan,nan,nan,nan,45.000,nan
23680,14,5000000.000,59.000,2019-04-04T00:00:00,3,2.500,5.000,52.000,1,0,...,0,Санкт-Петербург,26835.000,11878.000,0.000,nan,0.000,nan,nan,0.881
23681,13,5250000.000,43.000,2018-05-11T00:00:00,2,2.500,5.000,29.000,2,0,...,0,Санкт-Петербург,28323.000,7262.000,1.000,497.000,2.000,660.000,80.000,0.674
23682,11,2350000.000,35.600,2016-06-23T00:00:00,1,2.500,5.000,17.000,4,0,...,2,Выборг,nan,nan,nan,nan,nan,nan,40.000,0.478
23683,16,2100000.000,62.800,2018-09-18T00:00:00,4,2.500,5.000,45.500,3,0,...,0,посёлок Дзержинского,nan,nan,nan,nan,nan,nan,nan,0.725
23684,20,21400000.000,145.000,2018-11-02T00:00:00,4,3.000,26.000,71.400,17,0,...,0,Санкт-Петербург,11827.000,11459.000,0.000,nan,0.000,nan,nan,0.492
23685,15,2490000.000,31.000,2019-01-24T00:00:00,1,2.500,5.000,17.300,5,0,...,1,Ломоносов,48393.000,51818.000,0.000,nan,0.000,nan,nan,0.558
23686,8,3300000.000,31.000,2017-04-29T00:00:00,1,2.550,9.000,18.000,6,0,...,0,Санкт-Петербург,11751.000,11602.000,1.000,140.000,1.000,317.000,193.000,0.581
23687,6,3200000.000,39.000,2017-12-16T00:00:00,1,nan,9.000,20.000,6,0,...,2,Санкт-Петербург,40837.000,16704.000,0.000,nan,0.000,nan,38.000,0.513
23688,19,9200000.000,101.000,2019-04-01T00:00:00,3,3.050,15.000,63.000,12,0,...,0,Санкт-Петербург,15632.000,14428.000,0.000,nan,0.000,nan,23.000,0.624
23689,13,3550000.000,35.300,2018-02-28T00:00:00,1,2.860,15.000,16.300,4,0,...,2,Санкт-Петербург,17284.000,16081.000,1.000,353.000,2.000,652.000,29.000,0.462
23690,3,5500000.000,52.000,2018-07-19T00:00:00,2,nan,5.000,31.000,2,0,...,0,Санкт-Петербург,20151.000,6263.000,1.000,300.000,0.000,nan,15.000,0.596
23691,11,9470000.000,72.900,2016-10-13T00:00:00,2,2.750,25.000,40.300,7,0,...,1,Санкт-Петербург,19424.000,4489.000,0.000,nan,1.000,806.000,519.000,0.553
23692,2,1350000.000,30.000,2017-07-07T00:00:00,1,nan,5.000,17.500,4,0,...,0,Тихвин,nan,nan,nan,nan,nan,nan,413.000,0.583
23693,9,4600000.000,62.400,2016-08-05T00:00:00,3,2.600,9.000,40.000,8,0,...,0,Петергоф,45602.000,34104.000,1.000,352.000,1.000,675.000,239.000,0.641
23694,9,9700000.000,133.810,2017-03-21T00:00:00,3,3.700,5.000,73.300,3,0,...,0,Санкт-Петербург,24665.000,4232.000,1.000,796.000,3.000,381.000,nan,0.548
23695,14,3100000.000,59.000,2018-01-15T00:00:00,3,nan,5.000,38.000,4,0,...,0,Тосно,nan,nan,nan,nan,nan,nan,45.000,0.644
23696,18,2500000.000,56.700,2018-02-11T00:00:00,2,nan,3.000,29.700,1,0,...,0,село Рождествено,nan,nan,nan,nan,nan,nan,nan,0.524
23697,13,11475000.000,76.750,2017-03-28T00:00:00,2,3.000,17.000,nan,12,0,...,2,Санкт-Петербург,39140.000,10364.000,2.000,173.000,3.000,196.000,602.000,nan
23698,4,1350000.000,32.300,2017-07-21T00:00:00,1,2.500,5.000,12.300,1,0,...,0,поселок Новый Учхоз,nan,nan,nan,nan,nan,nan,nan,0.381

In [9]:
pd.read_csv('real_estate_data.csv',sep='\t').\
assign(
    balcony = lambda x: x['balcony'].fillna(0).astype(int),
    is_apartment = lambda x: x['is_apartment'].fillna(0).astype(int),
    open_plan = lambda x: x['open_plan'].fillna(0).astype(int),
    studio = lambda x: x['studio'].fillna(0).astype(int),
    living_to_total = lambda x: x['living_area'] / x['total_area']
)

,total_images,last_price,total_area,first_day_exposition,rooms,ceiling_height,floors_total,living_area,floor,is_apartment,...,balcony,locality_name,airports_nearest,cityCenters_nearest,parks_around3000,parks_nearest,ponds_around3000,ponds_nearest,days_exposition,living_to_total
0,20,13000000.000,108.000,2019-03-07T00:00:00,3,2.700,16.000,51.000,8,0,...,0,Санкт-Петербург,18863.000,16028.000,1.000,482.000,2.000,755.000,nan,0.472
1,7,3350000.000,40.400,2018-12-04T00:00:00,1,nan,11.000,18.600,1,0,...,2,посёлок Шушары,12817.000,18603.000,0.000,nan,0.000,nan,81.000,0.460
2,10,5196000.000,56.000,2015-08-20T00:00:00,2,nan,5.000,34.300,4,0,...,0,Санкт-Петербург,21741.000,13933.000,1.000,90.000,2.000,574.000,558.000,0.612
3,0,64900000.000,159.000,2015-07-24T00:00:00,3,nan,14.000,nan,9,0,...,0,Санкт-Петербург,28098.000,6800.000,2.000,84.000,3.000,234.000,424.000,nan
4,2,10000000.000,100.000,2018-06-19T00:00:00,2,3.030,14.000,32.000,13,0,...,0,Санкт-Петербург,31856.000,8098.000,2.000,112.000,1.000,48.000,121.000,0.320
5,10,2890000.000,30.400,2018-09-10T00:00:00,1,nan,12.000,14.400,5,0,...,0,городской посёлок Янино-1,nan,nan,nan,nan,nan,nan,55.000,0.474
6,6,3700000.000,37.300,2017-11-02T00:00:00,1,nan,26.000,10.600,6,0,...,1,посёлок Парголово,52996.000,19143.000,0.000,nan,0.000,nan,155.000,0.284
7,5,7915000.000,71.600,2019-04-18T00:00:00,2,nan,24.000,nan,22,0,...,2,Санкт-Петербург,23982.000,11634.000,0.000,nan,0.000,nan,nan,nan
8,20,2900000.000,33.160,2018-05-23T00:00:00,1,nan,27.000,15.430,26,0,...,0,посёлок Мурино,nan,nan,nan,nan,nan,nan,189.000,0.465
9,18,5400000.000,61.000,2017-02-26T00:00:00,3,2.500,9.000,43.600,7,0,...,2,Санкт-Петербург,50898.000,15008.000,0.000,nan,0.000,nan,289.000,0.715
10,5,5050000.000,39.600,2017-11-16T00:00:00,1,2.670,12.000,20.300,3,0,...,0,Санкт-Петербург,38357.000,13878.000,1.000,310.000,2.000,553.000,137.000,0.513
11,9,3300000.000,44.000,2018-08-27T00:00:00,2,nan,5.000,31.000,4,0,...,1,Ломоносов,48252.000,51677.000,0.000,nan,0.000,nan,7.000,0.705
12,10,3890000.000,54.000,2016-06-30T00:00:00,2,nan,5.000,30.000,5,0,...,0,Сертолово,nan,nan,nan,nan,nan,nan,90.000,0.556
13,20,3550000.000,42.800,2017-07-01T00:00:00,2,2.560,5.000,27.000,5,0,...,1,Петергоф,37868.000,33058.000,1.000,294.000,3.000,298.000,366.000,0.631
14,1,4400000.000,36.000,2016-06-23T00:00:00,1,nan,6.000,17.000,1,0,...,0,Пушкин,20782.000,30759.000,0.000,nan,1.000,96.000,203.000,0.472
15,16,4650000.000,39.000,2017-11-18T00:00:00,1,nan,14.000,20.500,5,0,...,1,Санкт-Петербург,12900.000,14259.000,1.000,590.000,1.000,296.000,19.000,0.526
16,11,6700000.000,82.000,2017-11-23T00:00:00,3,3.050,5.000,55.600,1,0,...,0,Санкт-Петербург,22108.000,10698.000,3.000,420.000,0.000,nan,397.000,0.678
17,6,4180000.000,36.000,2016-09-09T00:00:00,1,nan,17.000,16.500,7,0,...,1,Санкт-Петербург,33564.000,14616.000,0.000,nan,1.000,859.000,571.000,0.458
18,8,3250000.000,31.000,2017-01-27T00:00:00,1,2.500,5.000,19.400,2,0,...,1,Санкт-Петербург,44060.000,10842.000,1.000,759.000,0.000,nan,168.000,0.626
19,16,14200000.000,121.000,2019-01-09T00:00:00,3,2.750,16.000,76.000,8,0,...,0,Санкт-Петербург,38900.000,12843.000,0.000,nan,0.000,nan,97.000,0.628
20,12,6120000.000,80.000,2017-09-28T00:00:00,3,2.700,27.000,48.000,11,0,...,2,посёлок Парголово,53134.000,19311.000,0.000,nan,0.000,nan,74.000,0.600
21,13,3200000.000,31.600,2018-03-14T00:00:00,1,nan,5.000,16.900,2,0,...,1,Санкт-Петербург,36064.000,9722.000,1.000,248.000,0.000,nan,310.000,0.535
22,20,5000000.000,58.000,2017-04-24T00:00:00,2,2.750,25.000,30.000,15,0,...,2,деревня Кудрово,nan,nan,nan,nan,nan,nan,60.000,0.517
23,11,2950000.000,32.000,2016-10-29T00:00:00,1,2.600,9.000,17.700,9,0,...,0,Санкт-Петербург,15414.000,14211.000,2.000,517.000,1.000,190.000,615.000,0.553
24,8,6500000.000,97.200,2015-10-31T00:00:00,2,nan,3.000,46.500,1,0,...,0,Санкт-Петербург,20052.000,2336.000,3.000,411.000,3.000,124.000,265.000,0.478
25,3,6800000.000,76.000,2015-10-01T00:00:00,2,2.750,23.000,39.000,18,0,...,2,Санкт-Петербург,34967.000,14640.000,0.000,nan,1.000,564.000,300.000,0.513
26,6,4050000.000,60.000,2017-04-28T00:00:00,4,nan,5.000,43.000,4,0,...,0,Санкт-Петербург,11580.000,10510.000,0.000,nan,1.000,95.000,265.000,0.717
27,20,7100000.000,70.000,2017-05-12T00:00:00,3,2.600,17.000,49.000,11,0,...,0,Санкт-Петербург,29197.000,11456.000,2.000,452.000,1.000,779.000,151.000,0.700
28,8,4170000.000,44.000,2017-12-13T00:00:00,1,2.900,6.000,20.800,1,0,...,1,Пушкин,18557.000,30710.000,0.000,nan,1.000,118.000,74.000,0.473
29,9,8600000.000,100.000,2016-04-09T00:00:00,3,nan,19.000,52.000,15,0,...,0,Санкт-Петербург,30394.000,11526.000,1.000,532.000,1.000,896.000,125.000,0.520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23669,8,3000000.000,34.100,2017-11-10T00:00:00,1,nan,9.000,17.000,3,0,...,1,Колпино,24687.000,30473.000,0.000,nan,1.000,741.000,74.000,0.499
23670,9,2450000.000,45.600,2018-02-08T00:00:00,1,2.800,9.000,nan,2,0,...,0,поселок городского типа Синявино,nan,nan,nan,nan,nan,nan,45.000,nan
23671,3,3450000.000,35.300,2017-04-14T00:00:00,1,2.500,9.000,17.500,4,0,...,2,Санкт-Петербург,21435.000,15261.000,1.000,334.000,1.000,232.000,21.000,0.496
23672,5,3000000.000,30.800,2016-06-08T00:00:00,1,nan,5.000,16.100,3,0,...,0,Санкт-Петербург,44614.000,14193.000,2.000,258.000,0.000,nan,808.000,0.523
23673,9,3100000.000,23.000,2018-03-19T00:00:00,1,2.800,9.000,12.600,1,0,...,2,Санкт-Петербург,11813.000,11881.000,1.000,262.000,1.000,442.000,41.000,0.548
23674,10,5950000.000,56.000,2019-03-05T00:00:00,3,nan,8.000,32.100,3,0,...,0,Санкт-Петербург,32139.000,9217.000,0.000,nan,2.000,303.000,nan,0.573
23675,8,3550000.000,39.500,2016-10-03T00:00:00,1,nan,16.000,19.000,13,0,...,0,Санкт-Петербург,25740.000,14951.000,0.000,nan,0.000,nan,721.000,0.481
23676,19,3550000.000,36.400,2016-06-08T00:00:00,1,nan,16.000,14.900,13,0,...,0,Санкт-Петербург,32228.000,11884.000,1.000,701.000,0.000,nan,70.000,0.409
23677,8,2450000.000,35.000,2018-10-26T00:00:00,1,2.600,5.000,18.000,4,0,...,0,Всеволожск,nan,nan,nan,nan,nan,nan,28.000,0.514
23678,10,3500000.000,43.000,2016-05-19T00:00:00,2,2.500,3.000,26.100,2,0,...,1,Пушкин,15823.000,27977.000,0.000,nan,1.000,1134.000,252.000,0.607
23679,0,2500000.000,35.000,2017-12-08T00:00:00,1,nan,9.000,nan,4,0,...,0,Сосновый Бор,nan,nan,nan,nan,nan,nan,45.000,nan
23680,14,5000000.000,59.000,2019-04-04T00:00:00,3,2.500,5.000,52.000,1,0,...,0,Санкт-Петербург,26835.000,11878.000,0.000,nan,0.000,nan,nan,0.881
23681,13,5250000.000,43.000,2018-05-11T00:00:00,2,2.500,5.000,29.000,2,0,...,0,Санкт-Петербург,28323.000,7262.000,1.000,497.000,2.000,660.000,80.000,0.674
23682,11,2350000.000,35.600,2016-06-23T00:00:00,1,2.500,5.000,17.000,4,0,...,2,Выборг,nan,nan,nan,nan,nan,nan,40.000,0.478
23683,16,2100000.000,62.800,2018-09-18T00:00:00,4,2.500,5.000,45.500,3,0,...,0,посёлок Дзержинского,nan,nan,nan,nan,nan,nan,nan,0.725
23684,20,21400000.000,145.000,2018-11-02T00:00:00,4,3.000,26.000,71.400,17,0,...,0,Санкт-Петербург,11827.000,11459.000,0.000,nan,0.000,nan,nan,0.492
23685,15,2490000.000,31.000,2019-01-24T00:00:00,1,2.500,5.000,17.300,5,0,...,1,Ломоносов,48393.000,51818.000,0.000,nan,0.000,nan,nan,0.558
23686,8,3300000.000,31.000,2017-04-29T00:00:00,1,2.550,9.000,18.000,6,0,...,0,Санкт-Петербург,11751.000,11602.000,1.000,140.000,1.000,317.000,193.000,0.581
23687,6,3200000.000,39.000,2017-12-16T00:00:00,1,nan,9.000,20.000,6,0,...,2,Санкт-Петербург,40837.000,16704.000,0.000,nan,0.000,nan,38.000,0.513
23688,19,9200000.000,101.000,2019-04-01T00:00:00,3,3.050,15.000,63.000,12,0,...,0,Санкт-Петербург,15632.000,14428.000,0.000,nan,0.000,nan,23.000,0.624
23689,13,3550000.000,35.300,2018-02-28T00:00:00,1,2.860,15.000,16.300,4,0,...,2,Санкт-Петербург,17284.000,16081.000,1.000,353.000,2.000,652.000,29.000,0.462
23690,3,5500000.000,52.000,2018-07-19T00:00:00,2,nan,5.000,31.000,2,0,...,0,Санкт-Петербург,20151.000,6263.000,1.000,300.000,0.000,nan,15.000,0.596
23691,11,9470000.000,72.900,2016-10-13T00:00:00,2,2.750,25.000,40.300,7,0,...,1,Санкт-Петербург,19424.000,4489.000,0.000,nan,1.000,806.000,519.000,0.553
23692,2,1350000.000,30.000,2017-07-07T00:00:00,1,nan,5.000,17.500,4,0,...,0,Тихвин,nan,nan,nan,nan,nan,nan,413.000,0.583
23693,9,4600000.000,62.400,2016-08-05T00:00:00,3,2.600,9.000,40.000,8,0,...,0,Петергоф,45602.000,34104.000,1.000,352.000,1.000,675.000,239.000,0.641
23694,9,9700000.000,133.810,2017-03-21T00:00:00,3,3.700,5.000,73.300,3,0,...,0,Санкт-Петербург,24665.000,4232.000,1.000,796.000,3.000,381.000,nan,0.548
23695,14,3100000.000,59.000,2018-01-15T00:00:00,3,nan,5.000,38.000,4,0,...,0,Тосно,nan,nan,nan,nan,nan,nan,45.000,0.644
23696,18,2500000.000,56.700,2018-02-11T00:00:00,2,nan,3.000,29.700,1,0,...,0,село Рождествено,nan,nan,nan,nan,nan,nan,nan,0.524
23697,13,11475000.000,76.750,2017-03-28T00:00:00,2,3.000,17.000,nan,12,0,...,2,Санкт-Петербург,39140.000,10364.000,2.000,173.000,3.000,196.000,602.000,nan
23698,4,1350000.000,32.300,2017-07-21T00:00:00,1,2.500,5.000,12.300,1,0,...,0,поселок Новый Учхоз,nan,nan,nan,nan,nan,nan,nan,0.381

In [ ]:
for col in ['balcony', 'is_apartment', 'open_plan', 'studio']:
    df[col] = df[col].fillna(0).astype(int)

In [10]:
def fillna_and_convert_to_int(df,columns):
    df = df.copy()
    for col in columns:
        df[col] = df[col].fillna(0).astype(int)
    return df

In [11]:
pd.read_csv('real_estate_data.csv',sep='\t').\
pipe(abcd).\
pipe(fillna_and_convert_to_int,['balcony', 'is_apartment', 'open_plan', 'studio'])

,total_images,last_price,total_area,first_day_exposition,rooms,ceiling_height,floors_total,living_area,floor,is_apartment,...,kitchen_area,balcony,locality_name,airports_nearest,cityCenters_nearest,parks_around3000,parks_nearest,ponds_around3000,ponds_nearest,days_exposition
0,20,13000000.000,108.000,2019-03-07T00:00:00,3,2.700,16.000,51.000,8,0,...,25.000,0,Санкт-Петербург,18863.000,16028.000,1.000,482.000,2.000,755.000,nan
1,7,3350000.000,40.400,2018-12-04T00:00:00,1,nan,11.000,18.600,1,0,...,11.000,2,посёлок Шушары,12817.000,18603.000,0.000,nan,0.000,nan,81.000
2,10,5196000.000,56.000,2015-08-20T00:00:00,2,nan,5.000,34.300,4,0,...,8.300,0,Санкт-Петербург,21741.000,13933.000,1.000,90.000,2.000,574.000,558.000
3,0,64900000.000,159.000,2015-07-24T00:00:00,3,nan,14.000,nan,9,0,...,nan,0,Санкт-Петербург,28098.000,6800.000,2.000,84.000,3.000,234.000,424.000
4,2,10000000.000,100.000,2018-06-19T00:00:00,2,3.030,14.000,32.000,13,0,...,41.000,0,Санкт-Петербург,31856.000,8098.000,2.000,112.000,1.000,48.000,121.000
5,10,2890000.000,30.400,2018-09-10T00:00:00,1,nan,12.000,14.400,5,0,...,9.100,0,городской посёлок Янино-1,nan,nan,nan,nan,nan,nan,55.000
6,6,3700000.000,37.300,2017-11-02T00:00:00,1,nan,26.000,10.600,6,0,...,14.400,1,посёлок Парголово,52996.000,19143.000,0.000,nan,0.000,nan,155.000
7,5,7915000.000,71.600,2019-04-18T00:00:00,2,nan,24.000,nan,22,0,...,18.900,2,Санкт-Петербург,23982.000,11634.000,0.000,nan,0.000,nan,nan
8,20,2900000.000,33.160,2018-05-23T00:00:00,1,nan,27.000,15.430,26,0,...,8.810,0,посёлок Мурино,nan,nan,nan,nan,nan,nan,189.000
9,18,5400000.000,61.000,2017-02-26T00:00:00,3,2.500,9.000,43.600,7,0,...,6.500,2,Санкт-Петербург,50898.000,15008.000,0.000,nan,0.000,nan,289.000
10,5,5050000.000,39.600,2017-11-16T00:00:00,1,2.670,12.000,20.300,3,0,...,8.500,0,Санкт-Петербург,38357.000,13878.000,1.000,310.000,2.000,553.000,137.000
11,9,3300000.000,44.000,2018-08-27T00:00:00,2,nan,5.000,31.000,4,0,...,6.000,1,Ломоносов,48252.000,51677.000,0.000,nan,0.000,nan,7.000
12,10,3890000.000,54.000,2016-06-30T00:00:00,2,nan,5.000,30.000,5,0,...,9.000,0,Сертолово,nan,nan,nan,nan,nan,nan,90.000
13,20,3550000.000,42.800,2017-07-01T00:00:00,2,2.560,5.000,27.000,5,0,...,5.200,1,Петергоф,37868.000,33058.000,1.000,294.000,3.000,298.000,366.000
14,1,4400000.000,36.000,2016-06-23T00:00:00,1,nan,6.000,17.000,1,0,...,8.000,0,Пушкин,20782.000,30759.000,0.000,nan,1.000,96.000,203.000
15,16,4650000.000,39.000,2017-11-18T00:00:00,1,nan,14.000,20.500,5,0,...,7.600,1,Санкт-Петербург,12900.000,14259.000,1.000,590.000,1.000,296.000,19.000
16,11,6700000.000,82.000,2017-11-23T00:00:00,3,3.050,5.000,55.600,1,0,...,9.000,0,Санкт-Петербург,22108.000,10698.000,3.000,420.000,0.000,nan,397.000
17,6,4180000.000,36.000,2016-09-09T00:00:00,1,nan,17.000,16.500,7,0,...,11.000,1,Санкт-Петербург,33564.000,14616.000,0.000,nan,1.000,859.000,571.000
18,8,3250000.000,31.000,2017-01-27T00:00:00,1,2.500,5.000,19.400,2,0,...,5.600,1,Санкт-Петербург,44060.000,10842.000,1.000,759.000,0.000,nan,168.000
19,16,14200000.000,121.000,2019-01-09T00:00:00,3,2.750,16.000,76.000,8,0,...,12.000,0,Санкт-Петербург,38900.000,12843.000,0.000,nan,0.000,nan,97.000
20,12,6120000.000,80.000,2017-09-28T00:00:00,3,2.700,27.000,48.000,11,0,...,12.000,2,посёлок Парголово,53134.000,19311.000,0.000,nan,0.000,nan,74.000
21,13,3200000.000,31.600,2018-03-14T00:00:00,1,nan,5.000,16.900,2,0,...,5.700,1,Санкт-Петербург,36064.000,9722.000,1.000,248.000,0.000,nan,310.000
22,20,5000000.000,58.000,2017-04-24T00:00:00,2,2.750,25.000,30.000,15,0,...,11.000,2,деревня Кудрово,nan,nan,nan,nan,nan,nan,60.000
23,11,2950000.000,32.000,2016-10-29T00:00:00,1,2.600,9.000,17.700,9,0,...,6.100,0,Санкт-Петербург,15414.000,14211.000,2.000,517.000,1.000,190.000,615.000
24,8,6500000.000,97.200,2015-10-31T00:00:00,2,nan,3.000,46.500,1,0,...,19.600,0,Санкт-Петербург,20052.000,2336.000,3.000,411.000,3.000,124.000,265.000
25,3,6800000.000,76.000,2015-10-01T00:00:00,2,2.750,23.000,39.000,18,0,...,15.000,2,Санкт-Петербург,34967.000,14640.000,0.000,nan,1.000,564.000,300.000
26,6,4050000.000,60.000,2017-04-28T00:00:00,4,nan,5.000,43.000,4,0,...,7.000,0,Санкт-Петербург,11580.000,10510.000,0.000,nan,1.000,95.000,265.000
27,20,7100000.000,70.000,2017-05-12T00:00:00,3,2.600,17.000,49.000,11,0,...,9.200,0,Санкт-Петербург,29197.000,11456.000,2.000,452.000,1.000,779.000,151.000
28,8,4170000.000,44.000,2017-12-13T00:00:00,1,2.900,6.000,20.800,1,0,...,11.700,1,Пушкин,18557.000,30710.000,0.000,nan,1.000,118.000,74.000
29,9,8600000.000,100.000,2016-04-09T00:00:00,3,nan,19.000,52.000,15,0,...,11.000,0,Санкт-Петербург,30394.000,11526.000,1.000,532.000,1.000,896.000,125.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23669,8,3000000.000,34.100,2017-11-10T00:00:00,1,nan,9.000,17.000,3,0,...,9.000,1,Колпино,24687.000,30473.000,0.000,nan,1.000,741.000,74.000
23670,9,2450000.000,45.600,2018-02-08T00:00:00,1,2.800,9.000,nan,2,0,...,nan,0,поселок городского типа Синявино,nan,nan,nan,nan,nan,nan,45.000
23671,3,3450000.000,35.300,2017-04-14T00:00:00,1,2.500,9.000,17.500,4,0,...,7.500,2,Санкт-Петербург,21435.000,15261.000,1.000,334.000,1.000,232.000,21.000
23672,5,3000000.000,30.800,2016-06-08T00:00:00,1,nan,5.000,16.100,3,0,...,6.300,0,Санкт-Петербург,44614.000,14193.000,2.000,258.000,0.000,nan,808.000
23673,9,3100000.000,23.000,2018-03-19T00:00:00,1,2.800,9.000,12.600,1,0,...,5.000,2,Санкт-Петербург,11813.000,11881.000,1.000,262.000,1.000,442.000,41.000
23674,10,5950000.000,56.000,2019-03-05T00:00:00,3,nan,8.000,32.100,3,0,...,8.500,0,Санкт-Петербург,32139.000,9217.000,0.000,nan,2.000,303.000,nan
23675,8,3550000.000,39.500,2016-10-03T00:00:00,1,nan,16.000,19.000,13,0,...,8.500,0,Санкт-Петербург,25740.000,14951.000,0.000,nan,0.000,nan,721.000
23676,19,3550000.000,36.400,2016-06-08T00:00:00,1,nan,16.000,14.900,13,0,...,9.300,0,Санкт-Петербург,32228.000,11884.000,1.000,701.000,0.000,nan,70.000
23677,8,2450000.000,35.000,2018-10-26T00:00:00,1,2.600,5.000,18.000,4,0,...,9.600,0,Всеволожск,nan,nan,nan,nan,nan,nan,28.000
23678,10,3500000.000,43.000,2016-05-19T00:00:00,2,2.500,3.000,26.100,2,0,...,4.900,1,Пушкин,15823.000,27977.000,0.000,nan,1.000,1134.000,252.000
23679,0,2500000.000,35.000,2017-12-08T00:00:00,1,nan,9.000,nan,4,0,...,nan,0,Сосновый Бор,nan,nan,nan,nan,nan,nan,45.000
23680,14,5000000.000,59.000,2019-04-04T00:00:00,3,2.500,5.000,52.000,1,0,...,7.000,0,Санкт-Петербург,26835.000,11878.000,0.000,nan,0.000,nan,nan
23681,13,5250000.000,43.000,2018-05-11T00:00:00,2,2.500,5.000,29.000,2,0,...,6.000,0,Санкт-Петербург,28323.000,7262.000,1.000,497.000,2.000,660.000,80.000
23682,11,2350000.000,35.600,2016-06-23T00:00:00,1,2.500,5.000,17.000,4,0,...,8.300,2,Выборг,nan,nan,nan,nan,nan,nan,40.000
23683,16,2100000.000,62.800,2018-09-18T00:00:00,4,2.500,5.000,45.500,3,0,...,5.500,0,посёлок Дзержинского,nan,nan,nan,nan,nan,nan,nan
23684,20,21400000.000,145.000,2018-11-02T00:00:00,4,3.000,26.000,71.400,17,0,...,15.600,0,Санкт-Петербург,11827.000,11459.000,0.000,nan,0.000,nan,nan
23685,15,2490000.000,31.000,2019-01-24T00:00:00,1,2.500,5.000,17.300,5,0,...,5.600,1,Ломоносов,48393.000,51818.000,0.000,nan,0.000,nan,nan
23686,8,3300000.000,31.000,2017-04-29T00:00:00,1,2.550,9.000,18.000,6,0,...,6.500,0,Санкт-Петербург,11751.000,11602.000,1.000,140.000,1.000,317.000,193.000
23687,6,3200000.000,39.000,2017-12-16T00:00:00,1,nan,9.000,20.000,6,0,...,11.000,2,Санкт-Петербург,40837.000,16704.000,0.000,nan,0.000,nan,38.000
23688,19,9200000.000,101.000,2019-04-01T00:00:00,3,3.050,15.000,63.000,12,0,...,15.000,0,Санкт-Петербург,15632.000,14428.000,0.000,nan,0.000,nan,23.000
23689,13,3550000.000,35.300,2018-02-28T00:00:00,1,2.860,15.000,16.300,4,0,...,9.100,2,Санкт-Петербург,17284.000,16081.000,1.000,353.000,2.000,652.000,29.000
23690,3,5500000.000,52.000,2018-07-19T00:00:00,2,nan,5.000,31.000,2,0,...,6.000,0,Санкт-Петербург,20151.000,6263.000,1.000,300.000,0.000,nan,15.000
23691,11,9470000.000,72.900,2016-10-13T00:00:00,2,2.750,25.000,40.300,7,0,...,10.600,1,Санкт-Петербург,19424.000,4489.000,0.000,nan,1.000,806.000,519.000
23692,2,1350000.000,30.000,2017-07-07T00:00:00,1,nan,5.000,17.500,4,0,...,6.000,0,Тихвин,nan,nan,nan,nan,nan,nan,413.000
23693,9,4600000.000,62.400,2016-08-05T00:00:00,3,2.600,9.000,40.000,8,0,...,8.000,0,Петергоф,45602.000,34104.000,1.000,352.000,1.000,675.000,239.000
23694,9,9700000.000,133.810,2017-03-21T00:00:00,3,3.700,5.000,73.300,3,0,...,13.830,0,Санкт-Петербург,24665.000,4232.000,1.000,796.000,3.000,381.000,nan
23695,14,3100000.000,59.000,2018-01-15T00:00:00,3,nan,5.000,38.000,4,0,...,8.500,0,Тосно,nan,nan,nan,nan,nan,nan,45.000
23696,18,2500000.000,56.700,2018-02-11T00:00:00,2,nan,3.000,29.700,1,0,...,nan,0,село Рождествено,nan,nan,nan,nan,nan,nan,nan
23697,13,11475000.000,76.750,2017-03-28T00:00:00,2,3.000,17.000,nan,12,0,...,23.300,2,Санкт-Петербург,39140.000,10364.000,2.000,173.000,3.000,196.000,602.000
23698,4,1350000.000,32.300,2017-07-21T00:00:00,1,2.500,5.000,12.300,1,0,...,9.000,0,поселок Новый Учхоз,nan,nan,nan,nan,nan,nan,nan

In [12]:
other_function(fillna_and_convert_to_int(df,['balcony', 'is_apartment', 'open_plan', 'studio']),other_param)

,total_images,last_price,total_area,first_day_exposition,rooms,ceiling_height,floors_total,living_area,floor,is_apartment,...,kitchen_area,balcony,locality_name,airports_nearest,cityCenters_nearest,parks_around3000,parks_nearest,ponds_around3000,ponds_nearest,days_exposition
0,20,13000000.000,108.000,2019-03-07T00:00:00,3,2.700,16.000,51.000,8,0,...,25.000,0,Санкт-Петербург,18863.000,16028.000,1.000,482.000,2.000,755.000,nan
1,7,3350000.000,40.400,2018-12-04T00:00:00,1,nan,11.000,18.600,1,0,...,11.000,2,посёлок Шушары,12817.000,18603.000,0.000,nan,0.000,nan,81.000
2,10,5196000.000,56.000,2015-08-20T00:00:00,2,nan,5.000,34.300,4,0,...,8.300,0,Санкт-Петербург,21741.000,13933.000,1.000,90.000,2.000,574.000,558.000
3,0,64900000.000,159.000,2015-07-24T00:00:00,3,nan,14.000,nan,9,0,...,nan,0,Санкт-Петербург,28098.000,6800.000,2.000,84.000,3.000,234.000,424.000
4,2,10000000.000,100.000,2018-06-19T00:00:00,2,3.030,14.000,32.000,13,0,...,41.000,0,Санкт-Петербург,31856.000,8098.000,2.000,112.000,1.000,48.000,121.000
5,10,2890000.000,30.400,2018-09-10T00:00:00,1,nan,12.000,14.400,5,0,...,9.100,0,городской посёлок Янино-1,nan,nan,nan,nan,nan,nan,55.000
6,6,3700000.000,37.300,2017-11-02T00:00:00,1,nan,26.000,10.600,6,0,...,14.400,1,посёлок Парголово,52996.000,19143.000,0.000,nan,0.000,nan,155.000
7,5,7915000.000,71.600,2019-04-18T00:00:00,2,nan,24.000,nan,22,0,...,18.900,2,Санкт-Петербург,23982.000,11634.000,0.000,nan,0.000,nan,nan
8,20,2900000.000,33.160,2018-05-23T00:00:00,1,nan,27.000,15.430,26,0,...,8.810,0,посёлок Мурино,nan,nan,nan,nan,nan,nan,189.000
9,18,5400000.000,61.000,2017-02-26T00:00:00,3,2.500,9.000,43.600,7,0,...,6.500,2,Санкт-Петербург,50898.000,15008.000,0.000,nan,0.000,nan,289.000
10,5,5050000.000,39.600,2017-11-16T00:00:00,1,2.670,12.000,20.300,3,0,...,8.500,0,Санкт-Петербург,38357.000,13878.000,1.000,310.000,2.000,553.000,137.000
11,9,3300000.000,44.000,2018-08-27T00:00:00,2,nan,5.000,31.000,4,0,...,6.000,1,Ломоносов,48252.000,51677.000,0.000,nan,0.000,nan,7.000
12,10,3890000.000,54.000,2016-06-30T00:00:00,2,nan,5.000,30.000,5,0,...,9.000,0,Сертолово,nan,nan,nan,nan,nan,nan,90.000
13,20,3550000.000,42.800,2017-07-01T00:00:00,2,2.560,5.000,27.000,5,0,...,5.200,1,Петергоф,37868.000,33058.000,1.000,294.000,3.000,298.000,366.000
14,1,4400000.000,36.000,2016-06-23T00:00:00,1,nan,6.000,17.000,1,0,...,8.000,0,Пушкин,20782.000,30759.000,0.000,nan,1.000,96.000,203.000
15,16,4650000.000,39.000,2017-11-18T00:00:00,1,nan,14.000,20.500,5,0,...,7.600,1,Санкт-Петербург,12900.000,14259.000,1.000,590.000,1.000,296.000,19.000
16,11,6700000.000,82.000,2017-11-23T00:00:00,3,3.050,5.000,55.600,1,0,...,9.000,0,Санкт-Петербург,22108.000,10698.000,3.000,420.000,0.000,nan,397.000
17,6,4180000.000,36.000,2016-09-09T00:00:00,1,nan,17.000,16.500,7,0,...,11.000,1,Санкт-Петербург,33564.000,14616.000,0.000,nan,1.000,859.000,571.000
18,8,3250000.000,31.000,2017-01-27T00:00:00,1,2.500,5.000,19.400,2,0,...,5.600,1,Санкт-Петербург,44060.000,10842.000,1.000,759.000,0.000,nan,168.000
19,16,14200000.000,121.000,2019-01-09T00:00:00,3,2.750,16.000,76.000,8,0,...,12.000,0,Санкт-Петербург,38900.000,12843.000,0.000,nan,0.000,nan,97.000
20,12,6120000.000,80.000,2017-09-28T00:00:00,3,2.700,27.000,48.000,11,0,...,12.000,2,посёлок Парголово,53134.000,19311.000,0.000,nan,0.000,nan,74.000
21,13,3200000.000,31.600,2018-03-14T00:00:00,1,nan,5.000,16.900,2,0,...,5.700,1,Санкт-Петербург,36064.000,9722.000,1.000,248.000,0.000,nan,310.000
22,20,5000000.000,58.000,2017-04-24T00:00:00,2,2.750,25.000,30.000,15,0,...,11.000,2,деревня Кудрово,nan,nan,nan,nan,nan,nan,60.000
23,11,2950000.000,32.000,2016-10-29T00:00:00,1,2.600,9.000,17.700,9,0,...,6.100,0,Санкт-Петербург,15414.000,14211.000,2.000,517.000,1.000,190.000,615.000
24,8,6500000.000,97.200,2015-10-31T00:00:00,2,nan,3.000,46.500,1,0,...,19.600,0,Санкт-Петербург,20052.000,2336.000,3.000,411.000,3.000,124.000,265.000
25,3,6800000.000,76.000,2015-10-01T00:00:00,2,2.750,23.000,39.000,18,0,...,15.000,2,Санкт-Петербург,34967.000,14640.000,0.000,nan,1.000,564.000,300.000
26,6,4050000.000,60.000,2017-04-28T00:00:00,4,nan,5.000,43.000,4,0,...,7.000,0,Санкт-Петербург,11580.000,10510.000,0.000,nan,1.000,95.000,265.000
27,20,7100000.000,70.000,2017-05-12T00:00:00,3,2.600,17.000,49.000,11,0,...,9.200,0,Санкт-Петербург,29197.000,11456.000,2.000,452.000,1.000,779.000,151.000
28,8,4170000.000,44.000,2017-12-13T00:00:00,1,2.900,6.000,20.800,1,0,...,11.700,1,Пушкин,18557.000,30710.000,0.000,nan,1.000,118.000,74.000
29,9,8600000.000,100.000,2016-04-09T00:00:00,3,nan,19.000,52.000,15,0,...,11.000,0,Санкт-Петербург,30394.000,11526.000,1.000,532.000,1.000,896.000,125.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23669,8,3000000.000,34.100,2017-11-10T00:00:00,1,nan,9.000,17.000,3,0,...,9.000,1,Колпино,24687.000,30473.000,0.000,nan,1.000,741.000,74.000
23670,9,2450000.000,45.600,2018-02-08T00:00:00,1,2.800,9.000,nan,2,0,...,nan,0,поселок городского типа Синявино,nan,nan,nan,nan,nan,nan,45.000
23671,3,3450000.000,35.300,2017-04-14T00:00:00,1,2.500,9.000,17.500,4,0,...,7.500,2,Санкт-Петербург,21435.000,15261.000,1.000,334.000,1.000,232.000,21.000
23672,5,3000000.000,30.800,2016-06-08T00:00:00,1,nan,5.000,16.100,3,0,...,6.300,0,Санкт-Петербург,44614.000,14193.000,2.000,258.000,0.000,nan,808.000
23673,9,3100000.000,23.000,2018-03-19T00:00:00,1,2.800,9.000,12.600,1,0,...,5.000,2,Санкт-Петербург,11813.000,11881.000,1.000,262.000,1.000,442.000,41.000
23674,10,5950000.000,56.000,2019-03-05T00:00:00,3,nan,8.000,32.100,3,0,...,8.500,0,Санкт-Петербург,32139.000,9217.000,0.000,nan,2.000,303.000,nan
23675,8,3550000.000,39.500,2016-10-03T00:00:00,1,nan,16.000,19.000,13,0,...,8.500,0,Санкт-Петербург,25740.000,14951.000,0.000,nan,0.000,nan,721.000
23676,19,3550000.000,36.400,2016-06-08T00:00:00,1,nan,16.000,14.900,13,0,...,9.300,0,Санкт-Петербург,32228.000,11884.000,1.000,701.000,0.000,nan,70.000
23677,8,2450000.000,35.000,2018-10-26T00:00:00,1,2.600,5.000,18.000,4,0,...,9.600,0,Всеволожск,nan,nan,nan,nan,nan,nan,28.000
23678,10,3500000.000,43.000,2016-05-19T00:00:00,2,2.500,3.000,26.100,2,0,...,4.900,1,Пушкин,15823.000,27977.000,0.000,nan,1.000,1134.000,252.000
23679,0,2500000.000,35.000,2017-12-08T00:00:00,1,nan,9.000,nan,4,0,...,nan,0,Сосновый Бор,nan,nan,nan,nan,nan,nan,45.000
23680,14,5000000.000,59.000,2019-04-04T00:00:00,3,2.500,5.000,52.000,1,0,...,7.000,0,Санкт-Петербург,26835.000,11878.000,0.000,nan,0.000,nan,nan
23681,13,5250000.000,43.000,2018-05-11T00:00:00,2,2.500,5.000,29.000,2,0,...,6.000,0,Санкт-Петербург,28323.000,7262.000,1.000,497.000,2.000,660.000,80.000
23682,11,2350000.000,35.600,2016-06-23T00:00:00,1,2.500,5.000,17.000,4,0,...,8.300,2,Выборг,nan,nan,nan,nan,nan,nan,40.000
23683,16,2100000.000,62.800,2018-09-18T00:00:00,4,2.500,5.000,45.500,3,0,...,5.500,0,посёлок Дзержинского,nan,nan,nan,nan,nan,nan,nan
23684,20,21400000.000,145.000,2018-11-02T00:00:00,4,3.000,26.000,71.400,17,0,...,15.600,0,Санкт-Петербург,11827.000,11459.000,0.000,nan,0.000,nan,nan
23685,15,2490000.000,31.000,2019-01-24T00:00:00,1,2.500,5.000,17.300,5,0,...,5.600,1,Ломоносов,48393.000,51818.000,0.000,nan,0.000,nan,nan
23686,8,3300000.000,31.000,2017-04-29T00:00:00,1,2.550,9.000,18.000,6,0,...,6.500,0,Санкт-Петербург,11751.000,11602.000,1.000,140.000,1.000,317.000,193.000
23687,6,3200000.000,39.000,2017-12-16T00:00:00,1,nan,9.000,20.000,6,0,...,11.000,2,Санкт-Петербург,40837.000,16704.000,0.000,nan,0.000,nan,38.000
23688,19,9200000.000,101.000,2019-04-01T00:00:00,3,3.050,15.000,63.000,12,0,...,15.000,0,Санкт-Петербург,15632.000,14428.000,0.000,nan,0.000,nan,23.000
23689,13,3550000.000,35.300,2018-02-28T00:00:00,1,2.860,15.000,16.300,4,0,...,9.100,2,Санкт-Петербург,17284.000,16081.000,1.000,353.000,2.000,652.000,29.000
23690,3,5500000.000,52.000,2018-07-19T00:00:00,2,nan,5.000,31.000,2,0,...,6.000,0,Санкт-Петербург,20151.000,6263.000,1.000,300.000,0.000,nan,15.000
23691,11,9470000.000,72.900,2016-10-13T00:00:00,2,2.750,25.000,40.300,7,0,...,10.600,1,Санкт-Петербург,19424.000,4489.000,0.000,nan,1.000,806.000,519.000
23692,2,1350000.000,30.000,2017-07-07T00:00:00,1,nan,5.000,17.500,4,0,...,6.000,0,Тихвин,nan,nan,nan,nan,nan,nan,413.000
23693,9,4600000.000,62.400,2016-08-05T00:00:00,3,2.600,9.000,40.000,8,0,...,8.000,0,Петергоф,45602.000,34104.000,1.000,352.000,1.000,675.000,239.000
23694,9,9700000.000,133.810,2017-03-21T00:00:00,3,3.700,5.000,73.300,3,0,...,13.830,0,Санкт-Петербург,24665.000,4232.000,1.000,796.000,3.000,381.000,nan
23695,14,3100000.000,59.000,2018-01-15T00:00:00,3,nan,5.000,38.000,4,0,...,8.500,0,Тосно,nan,nan,nan,nan,nan,nan,45.000
23696,18,2500000.000,56.700,2018-02-11T00:00:00,2,nan,3.000,29.700,1,0,...,nan,0,село Рождествено,nan,nan,nan,nan,nan,nan,nan
23697,13,11475000.000,76.750,2017-03-28T00:00:00,2,3.000,17.000,nan,12,0,...,23.300,2,Санкт-Петербург,39140.000,10364.000,2.000,173.000,3.000,196.000,602.000
23698,4,1350000.000,32.300,2017-07-21T00:00:00,1,2.500,5.000,12.300,1,0,...,9.000,0,поселок Новый Учхоз,nan,nan,nan,nan,nan,nan,nan

func(func1(func2(df)))

In [ ]:
df.func1().\
func2().\
func3()

In [16]:
def create_floor_group(df):
    if df['floor'] == 1:
        return 1
    elif df['floor'] == df['floors_total']:
        return 3
    else:
        return 2

In [17]:
pd.read_csv('real_estate_data.csv',sep='\t').\
pipe(fillna_and_convert_to_int,['balcony', 'is_apartment', 'open_plan', 'studio']).\
assign(first_day_exposition = lambda x: pd.to_datetime(x['first_day_exposition'],format='%Y-%m-%dT%H:%M:%S'),
      floor_group = lambda x: x.apply(create_floor_group, axis=1))

,total_images,last_price,total_area,first_day_exposition,rooms,ceiling_height,floors_total,living_area,floor,is_apartment,...,balcony,locality_name,airports_nearest,cityCenters_nearest,parks_around3000,parks_nearest,ponds_around3000,ponds_nearest,days_exposition,floor_group
0,20,13000000.000,108.000,2019-03-07,3,2.700,16.000,51.000,8,0,...,0,Санкт-Петербург,18863.000,16028.000,1.000,482.000,2.000,755.000,nan,2
1,7,3350000.000,40.400,2018-12-04,1,nan,11.000,18.600,1,0,...,2,посёлок Шушары,12817.000,18603.000,0.000,nan,0.000,nan,81.000,1
2,10,5196000.000,56.000,2015-08-20,2,nan,5.000,34.300,4,0,...,0,Санкт-Петербург,21741.000,13933.000,1.000,90.000,2.000,574.000,558.000,2
3,0,64900000.000,159.000,2015-07-24,3,nan,14.000,nan,9,0,...,0,Санкт-Петербург,28098.000,6800.000,2.000,84.000,3.000,234.000,424.000,2
4,2,10000000.000,100.000,2018-06-19,2,3.030,14.000,32.000,13,0,...,0,Санкт-Петербург,31856.000,8098.000,2.000,112.000,1.000,48.000,121.000,2
5,10,2890000.000,30.400,2018-09-10,1,nan,12.000,14.400,5,0,...,0,городской посёлок Янино-1,nan,nan,nan,nan,nan,nan,55.000,2
6,6,3700000.000,37.300,2017-11-02,1,nan,26.000,10.600,6,0,...,1,посёлок Парголово,52996.000,19143.000,0.000,nan,0.000,nan,155.000,2
7,5,7915000.000,71.600,2019-04-18,2,nan,24.000,nan,22,0,...,2,Санкт-Петербург,23982.000,11634.000,0.000,nan,0.000,nan,nan,2
8,20,2900000.000,33.160,2018-05-23,1,nan,27.000,15.430,26,0,...,0,посёлок Мурино,nan,nan,nan,nan,nan,nan,189.000,2
9,18,5400000.000,61.000,2017-02-26,3,2.500,9.000,43.600,7,0,...,2,Санкт-Петербург,50898.000,15008.000,0.000,nan,0.000,nan,289.000,2
10,5,5050000.000,39.600,2017-11-16,1,2.670,12.000,20.300,3,0,...,0,Санкт-Петербург,38357.000,13878.000,1.000,310.000,2.000,553.000,137.000,2
11,9,3300000.000,44.000,2018-08-27,2,nan,5.000,31.000,4,0,...,1,Ломоносов,48252.000,51677.000,0.000,nan,0.000,nan,7.000,2
12,10,3890000.000,54.000,2016-06-30,2,nan,5.000,30.000,5,0,...,0,Сертолово,nan,nan,nan,nan,nan,nan,90.000,3
13,20,3550000.000,42.800,2017-07-01,2,2.560,5.000,27.000,5,0,...,1,Петергоф,37868.000,33058.000,1.000,294.000,3.000,298.000,366.000,3
14,1,4400000.000,36.000,2016-06-23,1,nan,6.000,17.000,1,0,...,0,Пушкин,20782.000,30759.000,0.000,nan,1.000,96.000,203.000,1
15,16,4650000.000,39.000,2017-11-18,1,nan,14.000,20.500,5,0,...,1,Санкт-Петербург,12900.000,14259.000,1.000,590.000,1.000,296.000,19.000,2
16,11,6700000.000,82.000,2017-11-23,3,3.050,5.000,55.600,1,0,...,0,Санкт-Петербург,22108.000,10698.000,3.000,420.000,0.000,nan,397.000,1
17,6,4180000.000,36.000,2016-09-09,1,nan,17.000,16.500,7,0,...,1,Санкт-Петербург,33564.000,14616.000,0.000,nan,1.000,859.000,571.000,2
18,8,3250000.000,31.000,2017-01-27,1,2.500,5.000,19.400,2,0,...,1,Санкт-Петербург,44060.000,10842.000,1.000,759.000,0.000,nan,168.000,2
19,16,14200000.000,121.000,2019-01-09,3,2.750,16.000,76.000,8,0,...,0,Санкт-Петербург,38900.000,12843.000,0.000,nan,0.000,nan,97.000,2
20,12,6120000.000,80.000,2017-09-28,3,2.700,27.000,48.000,11,0,...,2,посёлок Парголово,53134.000,19311.000,0.000,nan,0.000,nan,74.000,2
21,13,3200000.000,31.600,2018-03-14,1,nan,5.000,16.900,2,0,...,1,Санкт-Петербург,36064.000,9722.000,1.000,248.000,0.000,nan,310.000,2
22,20,5000000.000,58.000,2017-04-24,2,2.750,25.000,30.000,15,0,...,2,деревня Кудрово,nan,nan,nan,nan,nan,nan,60.000,2
23,11,2950000.000,32.000,2016-10-29,1,2.600,9.000,17.700,9,0,...,0,Санкт-Петербург,15414.000,14211.000,2.000,517.000,1.000,190.000,615.000,3
24,8,6500000.000,97.200,2015-10-31,2,nan,3.000,46.500,1,0,...,0,Санкт-Петербург,20052.000,2336.000,3.000,411.000,3.000,124.000,265.000,1
25,3,6800000.000,76.000,2015-10-01,2,2.750,23.000,39.000,18,0,...,2,Санкт-Петербург,34967.000,14640.000,0.000,nan,1.000,564.000,300.000,2
26,6,4050000.000,60.000,2017-04-28,4,nan,5.000,43.000,4,0,...,0,Санкт-Петербург,11580.000,10510.000,0.000,nan,1.000,95.000,265.000,2
27,20,7100000.000,70.000,2017-05-12,3,2.600,17.000,49.000,11,0,...,0,Санкт-Петербург,29197.000,11456.000,2.000,452.000,1.000,779.000,151.000,2
28,8,4170000.000,44.000,2017-12-13,1,2.900,6.000,20.800,1,0,...,1,Пушкин,18557.000,30710.000,0.000,nan,1.000,118.000,74.000,1
29,9,8600000.000,100.000,2016-04-09,3,nan,19.000,52.000,15,0,...,0,Санкт-Петербург,30394.000,11526.000,1.000,532.000,1.000,896.000,125.000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23669,8,3000000.000,34.100,2017-11-10,1,nan,9.000,17.000,3,0,...,1,Колпино,24687.000,30473.000,0.000,nan,1.000,741.000,74.000,2
23670,9,2450000.000,45.600,2018-02-08,1,2.800,9.000,nan,2,0,...,0,поселок городского типа Синявино,nan,nan,nan,nan,nan,nan,45.000,2
23671,3,3450000.000,35.300,2017-04-14,1,2.500,9.000,17.500,4,0,...,2,Санкт-Петербург,21435.000,15261.000,1.000,334.000,1.000,232.000,21.000,2
23672,5,3000000.000,30.800,2016-06-08,1,nan,5.000,16.100,3,0,...,0,Санкт-Петербург,44614.000,14193.000,2.000,258.000,0.000,nan,808.000,2
23673,9,3100000.000,23.000,2018-03-19,1,2.800,9.000,12.600,1,0,...,2,Санкт-Петербург,11813.000,11881.000,1.000,262.000,1.000,442.000,41.000,1
23674,10,5950000.000,56.000,2019-03-05,3,nan,8.000,32.100,3,0,...,0,Санкт-Петербург,32139.000,9217.000,0.000,nan,2.000,303.000,nan,2
23675,8,3550000.000,39.500,2016-10-03,1,nan,16.000,19.000,13,0,...,0,Санкт-Петербург,25740.000,14951.000,0.000,nan,0.000,nan,721.000,2
23676,19,3550000.000,36.400,2016-06-08,1,nan,16.000,14.900,13,0,...,0,Санкт-Петербург,32228.000,11884.000,1.000,701.000,0.000,nan,70.000,2
23677,8,2450000.000,35.000,2018-10-26,1,2.600,5.000,18.000,4,0,...,0,Всеволожск,nan,nan,nan,nan,nan,nan,28.000,2
23678,10,3500000.000,43.000,2016-05-19,2,2.500,3.000,26.100,2,0,...,1,Пушкин,15823.000,27977.000,0.000,nan,1.000,1134.000,252.000,2
23679,0,2500000.000,35.000,2017-12-08,1,nan,9.000,nan,4,0,...,0,Сосновый Бор,nan,nan,nan,nan,nan,nan,45.000,2
23680,14,5000000.000,59.000,2019-04-04,3,2.500,5.000,52.000,1,0,...,0,Санкт-Петербург,26835.000,11878.000,0.000,nan,0.000,nan,nan,1
23681,13,5250000.000,43.000,2018-05-11,2,2.500,5.000,29.000,2,0,...,0,Санкт-Петербург,28323.000,7262.000,1.000,497.000,2.000,660.000,80.000,2
23682,11,2350000.000,35.600,2016-06-23,1,2.500,5.000,17.000,4,0,...,2,Выборг,nan,nan,nan,nan,nan,nan,40.000,2
23683,16,2100000.000,62.800,2018-09-18,4,2.500,5.000,45.500,3,0,...,0,посёлок Дзержинского,nan,nan,nan,nan,nan,nan,nan,2
23684,20,21400000.000,145.000,2018-11-02,4,3.000,26.000,71.400,17,0,...,0,Санкт-Петербург,11827.000,11459.000,0.000,nan,0.000,nan,nan,2
23685,15,2490000.000,31.000,2019-01-24,1,2.500,5.000,17.300,5,0,...,1,Ломоносов,48393.000,51818.000,0.000,nan,0.000,nan,nan,3
23686,8,3300000.000,31.000,2017-04-29,1,2.550,9.000,18.000,6,0,...,0,Санкт-Петербург,11751.000,11602.000,1.000,140.000,1.000,317.000,193.000,2
23687,6,3200000.000,39.000,2017-12-16,1,nan,9.000,20.000,6,0,...,2,Санкт-Петербург,40837.000,16704.000,0.000,nan,0.000,nan,38.000,2
23688,19,9200000.000,101.000,2019-04-01,3,3.050,15.000,63.000,12,0,...,0,Санкт-Петербург,15632.000,14428.000,0.000,nan,0.000,nan,23.000,2
23689,13,3550000.000,35.300,2018-02-28,1,2.860,15.000,16.300,4,0,...,2,Санкт-Петербург,17284.000,16081.000,1.000,353.000,2.000,652.000,29.000,2
23690,3,5500000.000,52.000,2018-07-19,2,nan,5.000,31.000,2,0,...,0,Санкт-Петербург,20151.000,6263.000,1.000,300.000,0.000,nan,15.000,2
23691,11,9470000.000,72.900,2016-10-13,2,2.750,25.000,40.300,7,0,...,1,Санкт-Петербург,19424.000,4489.000,0.000,nan,1.000,806.000,519.000,2
23692,2,1350000.000,30.000,2017-07-07,1,nan,5.000,17.500,4,0,...,0,Тихвин,nan,nan,nan,nan,nan,nan,413.000,2
23693,9,4600000.000,62.400,2016-08-05,3,2.600,9.000,40.000,8,0,...,0,Петергоф,45602.000,34104.000,1.000,352.000,1.000,675.000,239.000,2
23694,9,9700000.000,133.810,2017-03-21,3,3.700,5.000,73.300,3,0,...,0,Санкт-Петербург,24665.000,4232.000,1.000,796.000,3.000,381.000,nan,2
23695,14,3100000.000,59.000,2018-01-15,3,nan,5.000,38.000,4,0,...,0,Тосно,nan,nan,nan,nan,nan,nan,45.000,2
23696,18,2500000.000,56.700,2018-02-11,2,nan,3.000,29.700,1,0,...,0,село Рождествено,nan,nan,nan,nan,nan,nan,nan,1
23697,13,11475000.000,76.750,2017-03-28,2,3.000,17.000,nan,12,0,...,2,Санкт-Петербург,39140.000,10364.000,2.000,173.000,3.000,196.000,602.000,2
23698,4,1350000.000,32.300,2017-07-21,1,2.500,5.000,12.300,1,0,...,0,поселок Новый Учхоз,nan,nan,nan,nan,nan,nan,nan,1

In [18]:
def make_new_params(df):
    """Добавляем новые параметры"""
    df = df.copy()
    df['price_per_area'] = df['last_price'] / df['total_area']
    df['kithcen_to_total']= df['kitchen_area'] / df['total_area']
    df['living_to_total'] = df['living_area'] / df['total_area']
    df['years_of_expositon'] = 
    return df

In [20]:
pd.read_csv('real_estate_data.csv',sep='\t').\
pipe(fillna_and_convert_to_int,['balcony', 'is_apartment', 'open_plan', 'studio']).\
pipe(make_new_params).\ # Добавляем новые параметры
assign(first_day_exposition = lambda x: pd.to_datetime(x['first_day_exposition'],format='%Y-%m-%dT%H:%M:%S'),
      floor_group = lambda x: x.apply(create_floor_group, axis=1))

,total_images,last_price,total_area,first_day_exposition,rooms,ceiling_height,floors_total,living_area,floor,is_apartment,...,cityCenters_nearest,parks_around3000,parks_nearest,ponds_around3000,ponds_nearest,days_exposition,price_per_area,kithcen_to_total,living_to_total,floor_group
0,20,13000000.000,108.000,2019-03-07,3,2.700,16.000,51.000,8,0,...,16028.000,1.000,482.000,2.000,755.000,nan,120370.370,0.231,0.472,2
1,7,3350000.000,40.400,2018-12-04,1,nan,11.000,18.600,1,0,...,18603.000,0.000,nan,0.000,nan,81.000,82920.792,0.272,0.460,1
2,10,5196000.000,56.000,2015-08-20,2,nan,5.000,34.300,4,0,...,13933.000,1.000,90.000,2.000,574.000,558.000,92785.714,0.148,0.612,2
3,0,64900000.000,159.000,2015-07-24,3,nan,14.000,nan,9,0,...,6800.000,2.000,84.000,3.000,234.000,424.000,408176.101,nan,nan,2
4,2,10000000.000,100.000,2018-06-19,2,3.030,14.000,32.000,13,0,...,8098.000,2.000,112.000,1.000,48.000,121.000,100000.000,0.410,0.320,2
5,10,2890000.000,30.400,2018-09-10,1,nan,12.000,14.400,5,0,...,nan,nan,nan,nan,nan,55.000,95065.789,0.299,0.474,2
6,6,3700000.000,37.300,2017-11-02,1,nan,26.000,10.600,6,0,...,19143.000,0.000,nan,0.000,nan,155.000,99195.710,0.386,0.284,2
7,5,7915000.000,71.600,2019-04-18,2,nan,24.000,nan,22,0,...,11634.000,0.000,nan,0.000,nan,nan,110544.693,0.264,nan,2
8,20,2900000.000,33.160,2018-05-23,1,nan,27.000,15.430,26,0,...,nan,nan,nan,nan,nan,189.000,87454.765,0.266,0.465,2
9,18,5400000.000,61.000,2017-02-26,3,2.500,9.000,43.600,7,0,...,15008.000,0.000,nan,0.000,nan,289.000,88524.590,0.107,0.715,2
10,5,5050000.000,39.600,2017-11-16,1,2.670,12.000,20.300,3,0,...,13878.000,1.000,310.000,2.000,553.000,137.000,127525.253,0.215,0.513,2
11,9,3300000.000,44.000,2018-08-27,2,nan,5.000,31.000,4,0,...,51677.000,0.000,nan,0.000,nan,7.000,75000.000,0.136,0.705,2
12,10,3890000.000,54.000,2016-06-30,2,nan,5.000,30.000,5,0,...,nan,nan,nan,nan,nan,90.000,72037.037,0.167,0.556,3
13,20,3550000.000,42.800,2017-07-01,2,2.560,5.000,27.000,5,0,...,33058.000,1.000,294.000,3.000,298.000,366.000,82943.925,0.121,0.631,3
14,1,4400000.000,36.000,2016-06-23,1,nan,6.000,17.000,1,0,...,30759.000,0.000,nan,1.000,96.000,203.000,122222.222,0.222,0.472,1
15,16,4650000.000,39.000,2017-11-18,1,nan,14.000,20.500,5,0,...,14259.000,1.000,590.000,1.000,296.000,19.000,119230.769,0.195,0.526,2
16,11,6700000.000,82.000,2017-11-23,3,3.050,5.000,55.600,1,0,...,10698.000,3.000,420.000,0.000,nan,397.000,81707.317,0.110,0.678,1
17,6,4180000.000,36.000,2016-09-09,1,nan,17.000,16.500,7,0,...,14616.000,0.000,nan,1.000,859.000,571.000,116111.111,0.306,0.458,2
18,8,3250000.000,31.000,2017-01-27,1,2.500,5.000,19.400,2,0,...,10842.000,1.000,759.000,0.000,nan,168.000,104838.710,0.181,0.626,2
19,16,14200000.000,121.000,2019-01-09,3,2.750,16.000,76.000,8,0,...,12843.000,0.000,nan,0.000,nan,97.000,117355.372,0.099,0.628,2
20,12,6120000.000,80.000,2017-09-28,3,2.700,27.000,48.000,11,0,...,19311.000,0.000,nan,0.000,nan,74.000,76500.000,0.150,0.600,2
21,13,3200000.000,31.600,2018-03-14,1,nan,5.000,16.900,2,0,...,9722.000,1.000,248.000,0.000,nan,310.000,101265.823,0.180,0.535,2
22,20,5000000.000,58.000,2017-04-24,2,2.750,25.000,30.000,15,0,...,nan,nan,nan,nan,nan,60.000,86206.897,0.190,0.517,2
23,11,2950000.000,32.000,2016-10-29,1,2.600,9.000,17.700,9,0,...,14211.000,2.000,517.000,1.000,190.000,615.000,92187.500,0.191,0.553,3
24,8,6500000.000,97.200,2015-10-31,2,nan,3.000,46.500,1,0,...,2336.000,3.000,411.000,3.000,124.000,265.000,66872.428,0.202,0.478,1
25,3,6800000.000,76.000,2015-10-01,2,2.750,23.000,39.000,18,0,...,14640.000,0.000,nan,1.000,564.000,300.000,89473.684,0.197,0.513,2
26,6,4050000.000,60.000,2017-04-28,4,nan,5.000,43.000,4,0,...,10510.000,0.000,nan,1.000,95.000,265.000,67500.000,0.117,0.717,2
27,20,7100000.000,70.000,2017-05-12,3,2.600,17.000,49.000,11,0,...,11456.000,2.000,452.000,1.000,779.000,151.000,101428.571,0.131,0.700,2
28,8,4170000.000,44.000,2017-12-13,1,2.900,6.000,20.800,1,0,...,30710.000,0.000,nan,1.000,118.000,74.000,94772.727,0.266,0.473,1
29,9,8600000.000,100.000,2016-04-09,3,nan,19.000,52.000,15,0,...,11526.000,1.000,532.000,1.000,896.000,125.000,86000.000,0.110,0.520,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23669,8,3000000.000,34.100,2017-11-10,1,nan,9.000,17.000,3,0,...,30473.000,0.000,nan,1.000,741.000,74.000,87976.540,0.264,0.499,2
23670,9,2450000.000,45.600,2018-02-08,1,2.800,9.000,nan,2,0,...,nan,nan,nan,nan,nan,45.000,53728.070,nan,nan,2
23671,3,3450000.000,35.300,2017-04-14,1,2.500,9.000,17.500,4,0,...,15261.000,1.000,334.000,1.000,232.000,21.000,97733.711,0.212,0.496,2
23672,5,3000000.000,30.800,2016-06-08,1,nan,5.000,16.100,3,0,...,14193.000,2.000,258.000,0.000,nan,808.000,97402.597,0.205,0.523,2
23673,9,3100000.000,23.000,2018-03-19,1,2.800,9.000,12.600,1,0,...,11881.000,1.000,262.000,1.000,442.000,41.000,134782.609,0.217,0.548,1
23674,10,5950000.000,56.000,2019-03-05,3,nan,8.000,32.100,3,0,...,9217.000,0.000,nan,2.000,303.000,nan,106250.000,0.152,0.573,2
23675,8,3550000.000,39.500,2016-10-03,1,nan,16.000,19.000,13,0,...,14951.000,0.000,nan,0.000,nan,721.000,89873.418,0.215,0.481,2
23676,19,3550000.000,36.400,2016-06-08,1,nan,16.000,14.900,13,0,...,11884.000,1.000,701.000,0.000,nan,70.000,97527.473,0.255,0.409,2
23677,8,2450000.000,35.000,2018-10-26,1,2.600,5.000,18.000,4,0,...,nan,nan,nan,nan,nan,28.000,70000.000,0.274,0.514,2
23678,10,3500000.000,43.000,2016-05-19,2,2.500,3.000,26.100,2,0,...,27977.000,0.000,nan,1.000,1134.000,252.000,81395.349,0.114,0.607,2
23679,0,2500000.000,35.000,2017-12-08,1,nan,9.000,nan,4,0,...,nan,nan,nan,nan,nan,45.000,71428.571,nan,nan,2
23680,14,5000000.000,59.000,2019-04-04,3,2.500,5.000,52.000,1,0,...,11878.000,0.000,nan,0.000,nan,nan,84745.763,0.119,0.881,1
23681,13,5250000.000,43.000,2018-05-11,2,2.500,5.000,29.000,2,0,...,7262.000,1.000,497.000,2.000,660.000,80.000,122093.023,0.140,0.674,2
23682,11,2350000.000,35.600,2016-06-23,1,2.500,5.000,17.000,4,0,...,nan,nan,nan,nan,nan,40.000,66011.236,0.233,0.478,2
23683,16,2100000.000,62.800,2018-09-18,4,2.500,5.000,45.500,3,0,...,nan,nan,nan,nan,nan,nan,33439.490,0.088,0.725,2
23684,20,21400000.000,145.000,2018-11-02,4,3.000,26.000,71.400,17,0,...,11459.000,0.000,nan,0.000,nan,nan,147586.207,0.108,0.492,2
23685,15,2490000.000,31.000,2019-01-24,1,2.500,5.000,17.300,5,0,...,51818.000,0.000,nan,0.000,nan,nan,80322.581,0.181,0.558,3
23686,8,3300000.000,31.000,2017-04-29,1,2.550,9.000,18.000,6,0,...,11602.000,1.000,140.000,1.000,317.000,193.000,106451.613,0.210,0.581,2
23687,6,3200000.000,39.000,2017-12-16,1,nan,9.000,20.000,6,0,...,16704.000,0.000,nan,0.000,nan,38.000,82051.282,0.282,0.513,2
23688,19,9200000.000,101.000,2019-04-01,3,3.050,15.000,63.000,12,0,...,14428.000,0.000,nan,0.000,nan,23.000,91089.109,0.149,0.624,2
23689,13,3550000.000,35.300,2018-02-28,1,2.860,15.000,16.300,4,0,...,16081.000,1.000,353.000,2.000,652.000,29.000,100566.572,0.258,0.462,2
23690,3,5500000.000,52.000,2018-07-19,2,nan,5.000,31.000,2,0,...,6263.000,1.000,300.000,0.000,nan,15.000,105769.231,0.115,0.596,2
23691,11,9470000.000,72.900,2016-10-13,2,2.750,25.000,40.300,7,0,...,4489.000,0.000,nan,1.000,806.000,519.000,129903.978,0.145,0.553,2
23692,2,1350000.000,30.000,2017-07-07,1,nan,5.000,17.500,4,0,...,nan,nan,nan,nan,nan,413.000,45000.000,0.200,0.583,2
23693,9,4600000.000,62.400,2016-08-05,3,2.600,9.000,40.000,8,0,...,34104.000,1.000,352.000,1.000,675.000,239.000,73717.949,0.128,0.641,2
23694,9,9700000.000,133.810,2017-03-21,3,3.700,5.000,73.300,3,0,...,4232.000,1.000,796.000,3.000,381.000,nan,72490.845,0.103,0.548,2
23695,14,3100000.000,59.000,2018-01-15,3,nan,5.000,38.000,4,0,...,nan,nan,nan,nan,nan,45.000,52542.373,0.144,0.644,2
23696,18,2500000.000,56.700,2018-02-11,2,nan,3.000,29.700,1,0,...,nan,nan,nan,nan,nan,nan,44091.711,nan,0.524,1
23697,13,11475000.000,76.750,2017-03-28,2,3.000,17.000,nan,12,0,...,10364.000,2.000,173.000,3.000,196.000,602.000,149511.401,0.304,nan,2
23698,4,1350000.000,32.300,2017-07-21,1,2.500,5.000,12.300,1,0,...,nan,nan,nan,nan,nan,nan,41795.666,0.279,0.381,1

In [22]:
def preproccessing(df):
    df = df.copy()
    df = df.\
        pipe(fillna_and_convert_to_int,['balcony', 'is_apartment', 'open_plan', 'studio']).\
        pipe(make_new_params).\
        assign(first_day_exposition = lambda x: pd.to_datetime(x['first_day_exposition'],format='%Y-%m-%dT%H:%M:%S'),
          floor_group = lambda x: x.apply(create_floor_group, axis=1))
    return df

In [23]:
proc_df = pd.read_csv('real_estate_data.csv',sep='\t').pipe(preproccessing)

In [24]:
proc_df_2 = proc_df[proc_df['last_price'] > proc_df['last_price'].median()]

In [25]:
grouped_df = proc_df_2.groupby(['floor_group','rooms']).agg({'total_area':'mean',
                                                             'last_price':'mean',
                                                            'total_images':'size'})
grouped_df

                   total_area    last_price  total_images
floor_group rooms
1           0          58.900   6225000.000             2
            1          51.205   6828820.207            82
            2          62.006   6806773.803           340
            3          75.079   7698526.479           426
            4          97.542   9353081.879           124
            5         128.490  13421465.600            40
            6         174.533  16369577.778             9
            7         257.100  29316815.200             5
            8         229.567  25063333.333             3
            9         399.000  68984450.000             2
2           0          81.711  14263222.222             9
            1          44.738   6176953.318          1416
            2          62.214   7679547.718          3346
            3          83.125   9857159.090          3427
            4         116.611  15886458.928           712
            5         162.364  23475438.010           207
            6         193.259  28921924.629            70
            7         256.949  38929189.189            37
            8         253.260  53940000.000             5
            9         272.550  23375000.000             4
            10        216.100  15500000.000             1
            11        194.100  33000000.000             1
            14        304.200  26829500.000             2
            15        590.000  65000000.000             1
            19        374.600  32250000.000             1
3           0          71.000   8200000.000             1
            1          45.145   6324513.696           135
            2          63.959   8248136.593           450
            3          84.338   9850703.592           593
            4         125.419  16420280.048           167
            5         191.606  34975976.818            66
            6         236.428  46130920.000            25
            7         285.976  85280588.235            17
            8         288.950  64450000.000             4
            9         279.800  20875000.000             2
            10        281.300  31500000.000             2
            11        183.700  17500000.000             1
            12        900.000 420000000.000             1
            16        270.000  28500000.000             1

In [ ]:
rename(columns={('total','sum'):('total_2','summa')})

In [26]:
grouped_df_2 = grouped_df.\
rename(columns={'total_images':'total_objects'}).\
reset_index().\
sort_values(['total_objects'],ascending=False)
grouped_df_2

    floor_group  rooms  total_area    last_price  total_objects
13            2      3      83.125   9857159.090           3427
12            2      2      62.214   7679547.718           3346
11            2      1      44.738   6176953.318           1416
14            2      4     116.611  15886458.928            712
28            3      3      84.338   9850703.592            593
27            3      2      63.959   8248136.593            450
3             1      3      75.079   7698526.479            426
2             1      2      62.006   6806773.803            340
15            2      5     162.364  23475438.010            207
29            3      4     125.419  16420280.048            167
26            3      1      45.145   6324513.696            135
4             1      4      97.542   9353081.879            124
1             1      1      51.205   6828820.207             82
16            2      6     193.259  28921924.629             70
30            3      5     191.606  34975976.818             66
5             1      5     128.490  13421465.600             40
17            2      7     256.949  38929189.189             37
31            3      6     236.428  46130920.000             25
32            3      7     285.976  85280588.235             17
6             1      6     174.533  16369577.778              9
10            2      0      81.711  14263222.222              9
18            2      8     253.260  53940000.000              5
7             1      7     257.100  29316815.200              5
33            3      8     288.950  64450000.000              4
19            2      9     272.550  23375000.000              4
8             1      8     229.567  25063333.333              3
34            3      9     279.800  20875000.000              2
35            3     10     281.300  31500000.000              2
0             1      0      58.900   6225000.000              2
22            2     14     304.200  26829500.000              2
9             1      9     399.000  68984450.000              2
25            3      0      71.000   8200000.000              1
24            2     19     374.600  32250000.000              1
23            2     15     590.000  65000000.000              1
21            2     11     194.100  33000000.000              1
20            2     10     216.100  15500000.000              1
36            3     11     183.700  17500000.000              1
37            3     12     900.000 420000000.000              1
38            3     16     270.000  28500000.000              1

In [27]:
grouped_df_2[grouped_df_2['total_objects'] > 100].\
assign(price_to_area_ratio = lambda x: x['last_price'] / x['total_area'])

,floor_group,rooms,total_area,last_price,total_objects,price_to_area_ratio
13,2,3,83.125,9857159.090,3427,118581.872
12,2,2,62.214,7679547.718,3346,123437.278
11,2,1,44.738,6176953.318,1416,138070.324
14,2,4,116.611,15886458.928,712,136234.359
28,3,3,84.338,9850703.592,593,116800.448
27,3,2,63.959,8248136.593,450,128959.077
3,1,3,75.079,7698526.479,426,102539.121
2,1,2,62.006,6806773.803,340,109776.884
15,2,5,162.364,23475438.010,207,144585.533
29,3,4,125.419,16420280.048,167,130923.654
26,3,1,45.145,6324513.696,135,140094.601
4,1,4,97.542,9353081.879,124,95888.199

In [28]:
proc_df.\
loc[proc_df['last_price'] > proc_df['last_price'].median()].\
groupby(['floor_group','rooms']).agg({'total_area':'mean',
                                       'last_price':'mean',
                                    'total_images':'size'}).\
rename(columns={'total_images':'total_objects'}).\
reset_index().\
sort_values(['total_objects'],ascending=False).\
loc[lambda x: x['total_objects'] > 100].\
assign(price_to_area_ratio = lambda x: x['last_price'] / x['total_area'])

,floor_group,rooms,total_area,last_price,total_objects,price_to_area_ratio
13,2,3,83.125,9857159.090,3427,118581.872
12,2,2,62.214,7679547.718,3346,123437.278
11,2,1,44.738,6176953.318,1416,138070.324
14,2,4,116.611,15886458.928,712,136234.359
28,3,3,84.338,9850703.592,593,116800.448
27,3,2,63.959,8248136.593,450,128959.077
3,1,3,75.079,7698526.479,426,102539.121
2,1,2,62.006,6806773.803,340,109776.884
15,2,5,162.364,23475438.010,207,144585.533
29,3,4,125.419,16420280.048,167,130923.654
26,3,1,45.145,6324513.696,135,140094.601
4,1,4,97.542,9353081.879,124,95888.199

In [ ]:
proc_df.\
loc[proc_df['last_price'] > proc_df['last_price'].median()].\
groupby(['floor_group','rooms']).agg({'total_area':'mean',
                                       'last_price':'mean',
                                    'total_images':'size'}).\
rename(columns={'total_images':'total_objects'}).\
reset_index().\
sort_values(['total_objects'],ascending=False).\
loc[lambda x: x['total_objects'] > 100].\
assign(price_to_area_ratio = lambda x: x['last_price'] / x['total_area'])

In [31]:
proc_df.\
loc[proc_df['last_price'] > proc_df['last_price'].median()].\
groupby(['floor_group','rooms']).agg({'total_area':'mean',
                                       'last_price':'mean',
                                    'total_images':'size'}).\
rename(columns={'total_images':'total_objects'}).\
reset_index().\
sort_values(['total_objects'],ascending=False).\
query('total_objects > 100').\
eval('price_to_area_ratio = last_price / total_area')

,floor_group,rooms,total_area,last_price,total_objects,price_to_area_ratio
13,2,3,83.125,9857159.090,3427,118581.872
12,2,2,62.214,7679547.718,3346,123437.278
11,2,1,44.738,6176953.318,1416,138070.324
14,2,4,116.611,15886458.928,712,136234.359
28,3,3,84.338,9850703.592,593,116800.448
27,3,2,63.959,8248136.593,450,128959.077
3,1,3,75.079,7698526.479,426,102539.121
2,1,2,62.006,6806773.803,340,109776.884
15,2,5,162.364,23475438.010,207,144585.533
29,3,4,125.419,16420280.048,167,130923.654
26,3,1,45.145,6324513.696,135,140094.601
4,1,4,97.542,9353081.879,124,95888.199

In [32]:
def show_df(df):
    df = df.copy()
    display(df)
    return df

In [34]:
proc_df.\
loc[proc_df['last_price'] > proc_df['last_price'].median()].\
pipe(show_df).\
groupby(['floor_group','rooms']).agg({'total_area':'mean',
                                       'last_price':'mean',
                                    'total_images':'size'}).\
rename(columns={'total_images':'total_objects'}).\
reset_index().\
sort_values(['total_objects'],ascending=False).\
pipe(show_df).\
query('total_objects > 100').\
eval('price_to_area_ratio = last_price / total_area')

,total_images,last_price,total_area,first_day_exposition,rooms,ceiling_height,floors_total,living_area,floor,is_apartment,...,cityCenters_nearest,parks_around3000,parks_nearest,ponds_around3000,ponds_nearest,days_exposition,price_per_area,kithcen_to_total,living_to_total,floor_group
0,20,13000000.000,108.000,2019-03-07,3,2.700,16.000,51.000,8,0,...,16028.000,1.000,482.000,2.000,755.000,nan,120370.370,0.231,0.472,2
2,10,5196000.000,56.000,2015-08-20,2,nan,5.000,34.300,4,0,...,13933.000,1.000,90.000,2.000,574.000,558.000,92785.714,0.148,0.612,2
3,0,64900000.000,159.000,2015-07-24,3,nan,14.000,nan,9,0,...,6800.000,2.000,84.000,3.000,234.000,424.000,408176.101,nan,nan,2
4,2,10000000.000,100.000,2018-06-19,2,3.030,14.000,32.000,13,0,...,8098.000,2.000,112.000,1.000,48.000,121.000,100000.000,0.410,0.320,2
7,5,7915000.000,71.600,2019-04-18,2,nan,24.000,nan,22,0,...,11634.000,0.000,nan,0.000,nan,nan,110544.693,0.264,nan,2
9,18,5400000.000,61.000,2017-02-26,3,2.500,9.000,43.600,7,0,...,15008.000,0.000,nan,0.000,nan,289.000,88524.590,0.107,0.715,2
10,5,5050000.000,39.600,2017-11-16,1,2.670,12.000,20.300,3,0,...,13878.000,1.000,310.000,2.000,553.000,137.000,127525.253,0.215,0.513,2
16,11,6700000.000,82.000,2017-11-23,3,3.050,5.000,55.600,1,0,...,10698.000,3.000,420.000,0.000,nan,397.000,81707.317,0.110,0.678,1
19,16,14200000.000,121.000,2019-01-09,3,2.750,16.000,76.000,8,0,...,12843.000,0.000,nan,0.000,nan,97.000,117355.372,0.099,0.628,2
20,12,6120000.000,80.000,2017-09-28,3,2.700,27.000,48.000,11,0,...,19311.000,0.000,nan,0.000,nan,74.000,76500.000,0.150,0.600,2
22,20,5000000.000,58.000,2017-04-24,2,2.750,25.000,30.000,15,0,...,nan,nan,nan,nan,nan,60.000,86206.897,0.190,0.517,2
24,8,6500000.000,97.200,2015-10-31,2,nan,3.000,46.500,1,0,...,2336.000,3.000,411.000,3.000,124.000,265.000,66872.428,0.202,0.478,1
25,3,6800000.000,76.000,2015-10-01,2,2.750,23.000,39.000,18,0,...,14640.000,0.000,nan,1.000,564.000,300.000,89473.684,0.197,0.513,2
27,20,7100000.000,70.000,2017-05-12,3,2.600,17.000,49.000,11,0,...,11456.000,2.000,452.000,1.000,779.000,151.000,101428.571,0.131,0.700,2
29,9,8600000.000,100.000,2016-04-09,3,nan,19.000,52.000,15,0,...,11526.000,1.000,532.000,1.000,896.000,125.000,86000.000,0.110,0.520,2
31,8,7200000.000,67.900,2017-10-26,2,2.800,16.000,38.100,4,0,...,12944.000,0.000,nan,0.000,nan,112.000,106038.292,0.197,0.561,2
32,7,4990000.000,60.000,2016-05-22,3,nan,5.000,39.000,4,0,...,12889.000,0.000,nan,1.000,426.000,224.000,83166.667,0.100,0.650,2
33,8,4800000.000,73.000,2018-10-15,4,nan,9.000,51.600,5,0,...,32321.000,0.000,nan,0.000,nan,92.000,65753.425,0.089,0.707,2
35,6,15500000.000,149.000,2017-06-26,5,nan,5.000,104.000,4,0,...,3502.000,0.000,nan,1.000,779.000,644.000,104026.846,0.114,0.698,2
39,15,5200000.000,54.400,2018-11-29,2,2.750,9.000,29.700,2,0,...,12209.000,0.000,nan,1.000,1175.000,29.000,95588.235,0.162,0.546,2
41,16,7900000.000,74.000,2016-05-04,3,nan,14.000,59.000,8,0,...,12612.000,1.000,725.000,1.000,759.000,179.000,106756.757,0.162,0.797,2
42,13,22000000.000,161.800,2015-07-08,4,2.800,4.000,80.900,2,0,...,30605.000,2.000,47.000,1.000,907.000,987.000,135970.334,0.109,0.500,2
43,13,9330000.000,48.000,2017-01-10,2,3.000,4.000,28.000,4,0,...,10822.000,0.000,nan,1.000,492.000,763.000,194375.000,0.156,0.583,3
44,13,5350000.000,40.000,2018-11-18,1,nan,22.000,nan,3,0,...,11603.000,1.000,620.000,1.000,1152.000,nan,133750.000,nan,nan,2
45,17,5200000.000,50.600,2018-12-02,2,2.650,9.000,30.300,7,0,...,12872.000,0.000,nan,0.000,nan,nan,102766.798,0.138,0.599,2
46,17,6600000.000,52.100,2019-01-31,2,2.600,24.000,29.700,9,0,...,12702.000,0.000,nan,0.000,nan,nan,126679.463,0.159,0.570,2
51,7,45000000.000,161.000,2017-10-17,3,3.200,8.000,38.000,4,0,...,6589.000,0.000,nan,3.000,99.000,541.000,279503.106,0.311,0.236,2
52,20,11795000.000,136.000,2017-09-22,6,3.000,2.000,94.000,2,0,...,6582.000,1.000,526.000,0.000,nan,nan,86727.941,0.081,0.691,3
55,20,7400000.000,58.800,2018-03-24,2,2.600,10.000,33.700,9,0,...,12260.000,0.000,nan,1.000,998.000,69.000,125850.340,0.182,0.573,2
59,15,6300000.000,46.500,2017-03-06,1,nan,13.000,nan,13,0,...,14501.000,0.000,nan,0.000,nan,336.000,135483.871,nan,nan,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23629,4,5650000.000,54.000,2017-04-30,2,2.750,12.000,28.000,4,0,...,12604.000,1.000,473.000,0.000,nan,193.000,104629.630,0.157,0.519,2
23631,17,14799000.000,104.000,2018-11-18,3,3.100,4.000,66.000,2,0,...,13944.000,0.000,nan,1.000,553.000,90.000,142298.077,0.135,0.635,2
23632,20,5000000.000,38.000,2018-06-23,1,2.550,16.000,nan,15,0,...,7257.000,1.000,241.000,1.000,230.000,113.000,131578.947,nan,nan,2
23635,9,5100000.000,36.000,2018-10-26,1,2.800,15.000,18.000,11,0,...,11673.000,0.000,nan,1.000,405.000,60.000,141666.667,0.222,0.500,2
23638,8,4920000.000,76.260,2014-12-25,3,nan,15.000,42.550,13,0,...,nan,nan,nan,nan,nan,939.000,64516.129,0.133,0.558,2
23642,14,5950000.000,80.300,2018-07-03,3,2.700,12.000,nan,5,0,...,33719.000,0.000,nan,2.000,562.000,60.000,74097.136,nan,nan,2
23644,7,4990000.000,62.500,2018-04-26,2,2.700,4.000,32.300,4,0,...,4415.000,1.000,560.000,1.000,171.000,166.000,79840.000,0.194,0.517,3
23646,10,8200000.000,68.700,2018-12-03,2,2.800,17.000,34.400,2,0,...,14691.000,0.000,nan,2.000,611.000,nan,119359.534,0.262,0.501,2
23647,9,5700000.000,45.600,2019-01-09,1,2.750,16.000,18.700,6,0,...,12551.000,0.000,nan,0.000,nan,8.000,125000.000,0.386,0.410,2
23648,14,10100000.000,78.000,2017-05-12,3,3.270,5.000,48.600,5,0,...,1113.000,1.000,621.000,2.000,117.000,621.000,129487.179,0.105,0.623,3
23650,20,10000000.000,84.200,2018-02-01,3,2.600,16.000,51.700,6,0,...,13302.000,0.000,nan,0.000,nan,nan,118764.846,0.141,0.614,2
23653,10,11000000.000,74.000,2018-11-04,2,2.500,18.000,40.000,10,0,...,12830.000,0.000,nan,0.000,nan,nan,148648.649,0.142,0.541,2
23657,2,5990000.000,64.000,2017-04-21,2,nan,19.000,31.000,16,0,...,14479.000,0.000,nan,1.000,1127.000,40.000,93593.750,0.172,0.484,2
23659,11,4900000.000,60.000,2015-12-15,3,2.600,15.000,39.500,2,0,...,10224.000,1.000,458.000,0.000,nan,252.000,81666.667,0.127,0.658,2
23661,19,8100000.000,75.400,2018-09-19,3,2.750,12.000,47.900,11,0,...,16771.000,0.000,nan,0.000,nan,6.000,107427.056,0.125,0.635,2
23662,0,6151120.000,66.860,2017-12-15,2,2.700,18.000,32.900,7,0,...,16275.000,1.000,684.000,1.000,861.000,203.000,92000.000,0.171,0.492,2
23663,12,6400000.000,88.000,2018-01-12,4,2.550,10.000,nan,1,0,...,13943.000,0.000,nan,2.000,844.000,59.000,72727.273,nan,nan,1
23664,5,9000000.000,110.000,2015-12-10,4,3.360,7.000,64.600,5,0,...,5016.000,3.000,417.000,1.000,118.000,816.000,81818.182,0.144,0.587,2
23666,9,8150000.000,80.000,2016-04-17,3,nan,17.000,44.900,12,0,...,nan,nan,nan,nan,nan,286.000,101875.000,0.143,0.561,2
23667,14,9990000.000,90.000,2017-01-23,3,3.060,17.000,55.000,9,0,...,33272.000,0.000,nan,1.000,545.000,86.000,111000.000,0.122,0.611,2
23668,13,6000000.000,47.000,2018-03-16,2,3.000,5.000,27.000,4,0,...,9167.000,2.000,238.000,0.000,nan,157.000,127659.574,0.191,0.574,2
23674,10,5950000.000,56.000,2019-03-05,3,nan,8.000,32.100,3,0,...,9217.000,0.000,nan,2.000,303.000,nan,106250.000,0.152,0.573,2
23680,14,5000000.000,59.000,2019-04-04,3,2.500,5.000,52.000,1,0,...,11878.000,0.000,nan,0.000,nan,nan,84745.763,0.119,0.881,1
23681,13,5250000.000,43.000,2018-05-11,2,2.500,5.000,29.000,2,0,...,7262.000,1.000,497.000,2.000,660.000,80.000,122093.023,0.140,0.674,2
23684,20,21400000.000,145.000,2018-11-02,4,3.000,26.000,71.400,17,0,...,11459.000,0.000,nan,0.000,nan,nan,147586.207,0.108,0.492,2
23688,19,9200000.000,101.000,2019-04-01,3,3.050,15.000,63.000,12,0,...,14428.000,0.000,nan,0.000,nan,23.000,91089.109,0.149,0.624,2
23690,3,5500000.000,52.000,2018-07-19,2,nan,5.000,31.000,2,0,...,6263.000,1.000,300.000,0.000,nan,15.000,105769.231,0.115,0.596,2
23691,11,9470000.000,72.900,2016-10-13,2,2.750,25.000,40.300,7,0,...,4489.000,0.000,nan,1.000,806.000,519.000,129903.978,0.145,0.553,2
23694,9,9700000.000,133.810,2017-03-21,3,3.700,5.000,73.300,3,0,...,4232.000,1.000,796.000,3.000,381.000,nan,72490.845,0.103,0.548,2
23697,13,11475000.000,76.750,2017-03-28,2,3.000,17.000,nan,12,0,...,10364.000,2.000,173.000,3.000,196.000,602.000,149511.401,0.304,nan,2

    floor_group  rooms  total_area    last_price  total_objects
13            2      3      83.125   9857159.090           3427
12            2      2      62.214   7679547.718           3346
11            2      1      44.738   6176953.318           1416
14            2      4     116.611  15886458.928            712
28            3      3      84.338   9850703.592            593
27            3      2      63.959   8248136.593            450
3             1      3      75.079   7698526.479            426
2             1      2      62.006   6806773.803            340
15            2      5     162.364  23475438.010            207
29            3      4     125.419  16420280.048            167
26            3      1      45.145   6324513.696            135
4             1      4      97.542   9353081.879            124
1             1      1      51.205   6828820.207             82
16            2      6     193.259  28921924.629             70
30            3      5     191.606  34975976.818             66
5             1      5     128.490  13421465.600             40
17            2      7     256.949  38929189.189             37
31            3      6     236.428  46130920.000             25
32            3      7     285.976  85280588.235             17
6             1      6     174.533  16369577.778              9
10            2      0      81.711  14263222.222              9
18            2      8     253.260  53940000.000              5
7             1      7     257.100  29316815.200              5
33            3      8     288.950  64450000.000              4
19            2      9     272.550  23375000.000              4
8             1      8     229.567  25063333.333              3
34            3      9     279.800  20875000.000              2
35            3     10     281.300  31500000.000              2
0             1      0      58.900   6225000.000              2
22            2     14     304.200  26829500.000              2
9             1      9     399.000  68984450.000              2
25            3      0      71.000   8200000.000              1
24            2     19     374.600  32250000.000              1
23            2     15     590.000  65000000.000              1
21            2     11     194.100  33000000.000              1
20            2     10     216.100  15500000.000              1
36            3     11     183.700  17500000.000              1
37            3     12     900.000 420000000.000              1
38            3     16     270.000  28500000.000              1

,floor_group,rooms,total_area,last_price,total_objects,price_to_area_ratio
13,2,3,83.125,9857159.090,3427,118581.872
12,2,2,62.214,7679547.718,3346,123437.278
11,2,1,44.738,6176953.318,1416,138070.324
14,2,4,116.611,15886458.928,712,136234.359
28,3,3,84.338,9850703.592,593,116800.448
27,3,2,63.959,8248136.593,450,128959.077
3,1,3,75.079,7698526.479,426,102539.121
2,1,2,62.006,6806773.803,340,109776.884
15,2,5,162.364,23475438.010,207,144585.533
29,3,4,125.419,16420280.048,167,130923.654
26,3,1,45.145,6324513.696,135,140094.601
4,1,4,97.542,9353081.879,124,95888.199

In [ ]:
df[['a','e']].\
merge(df2[['a','b','c']],how='left',on='a').\
merge(df3[['b','d']],how=)

In [ ]:
proc[proc_df['last_price'] > proc_df['last_price'].median()]
proc.loc[proc_df['last_price'] > proc_df['last_price'].median()]